/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Memeriksa kesiapan API dan basis data */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mendaftarkan depot baru beserta pemiliknya */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Masuk dengan nomor HP dan kata sandi */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Menukar token penyegar dengan sesi baru */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Keluar dari perangkat ini */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Keluar dari semua perangkat */
        post: operations["logoutAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pengguna dan depot yang sedang masuk */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mengganti kata sandi sendiri */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/depot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profil depot pemilik */
        get: operations["getDepot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mengubah pengaturan depot */
        patch: operations["updateDepot"];
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daftar pemilik dan kurir depot */
        get: operations["listUsers"];
        put?: never;
        /** Menambah akun kurir */
        post: operations["createCourier"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mengubah nama atau status aktif pengguna */
        patch: operations["updateUser"];
        trace?: never;
    };
    "/users/{id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Menyetel ulang kata sandi kurir */
        post: operations["resetUserPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Readiness: {
            /** @enum {string} */
            status: "ok";
            /** @enum {string} */
            database: "ok";
        };
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        ErrorBody: {
            /** @enum {string} */
            code: "validation_failed" | "unauthenticated" | "forbidden" | "not_found" | "conflict" | "invalid_transition" | "rate_limited" | "internal" | "unavailable";
            message: string;
            fields?: {
                [key: string]: string;
            };
        };
        Cursor: {
            next_cursor?: string | null;
        };
        FlagResponse: {
            data: {
                [key: string]: boolean;
            };
        };
        RegisterRequest: {
            depot_name: string;
            name: string;
            phone: string;
            password: string;
        };
        LoginRequest: {
            phone: string;
            password: string;
        };
        ChangePasswordRequest: {
            current_password: string;
            new_password: string;
        };
        /** @enum {string} */
        Role: "owner" | "courier";
        User: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            depot_id: string;
            role: components["schemas"]["Role"];
            name: string;
            phone: string;
            is_active: boolean;
            /** Format: date-time */
            last_login_at: string | null;
            /** Format: date-time */
            created_at: string;
        };
        UserResponse: {
            data: components["schemas"]["User"];
        };
        CreateCourierRequest: {
            name: string;
            phone: string;
            password: string;
        };
        UserUpdate: {
            name?: string;
            is_active?: boolean;
        };
        Depot: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            phone: string;
            address: string;
            lat: number | null;
            lng: number | null;
            timezone: string;
            /** @description Format HH:MM */
            open_time: string;
            /** @description Format HH:MM */
            close_time: string;
            delivery_fee: number;
            is_accepting_orders: boolean;
            auto_confirm_known: boolean;
            loyalty_every: number | null;
            reminder_lead_days: number;
            default_days_per_gallon: number;
            is_demo: boolean;
        };
        DepotResponse: {
            data: components["schemas"]["Depot"];
        };
        DepotUpdate: {
            name?: string;
            phone?: string;
            address?: string;
            lat?: number;
            lng?: number;
            open_time?: string;
            close_time?: string;
            delivery_fee?: number;
            is_accepting_orders?: boolean;
            auto_confirm_known?: boolean;
            /** @description 0 mematikan loyalitas */
            loyalty_every?: number;
            reminder_lead_days?: number;
            default_days_per_gallon?: number;
        };
        SessionResponse: {
            data: {
                user: components["schemas"]["User"];
                depot: components["schemas"]["Depot"];
            };
        };
    };
    responses: {
        /** @description Galat baku */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        Id: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Siap */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Readiness"];
                    };
                };
            };
            503: components["responses"]["Error"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Depot dibuat dan sesi dipasang di cookie */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            422: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Berhasil masuk */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            401: components["responses"]["Error"];
            409: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesi diperbarui */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlagResponse"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Keluar */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlagResponse"];
                };
            };
        };
    };
    logoutAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Keluar */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlagResponse"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesi aktif */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Kata sandi diganti */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlagResponse"];
                };
            };
            401: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    getDepot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Depot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepotResponse"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    updateDepot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepotUpdate"];
            };
        };
        responses: {
            /** @description Depot diperbarui */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepotResponse"];
                };
            };
            422: components["responses"]["Error"];
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar pengguna */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["User"][];
                    };
                };
            };
        };
    };
    createCourier: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCourierRequest"];
            };
        };
        responses: {
            /** @description Kurir dibuat */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            422: components["responses"]["Error"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Pengguna diperbarui */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            404: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    resetUserPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    password: string;
                };
            };
        };
        responses: {
            /** @description Kata sandi disetel ulang */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlagResponse"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
}
