/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Memeriksa kesiapan API dan basis data */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mendaftarkan depot baru beserta pemiliknya */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Masuk dengan nomor HP dan kata sandi */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Menukar token penyegar dengan sesi baru */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Keluar dari perangkat ini */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Keluar dari semua perangkat */
        post: operations["logoutAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pengguna dan depot yang sedang masuk */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mengganti kata sandi sendiri */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/depot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profil depot pemilik */
        get: operations["getDepot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mengubah pengaturan depot */
        patch: operations["updateDepot"];
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daftar pemilik dan kurir depot */
        get: operations["listUsers"];
        put?: never;
        /** Menambah akun kurir */
        post: operations["createCourier"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mengubah nama atau status aktif pengguna */
        patch: operations["updateUser"];
        trace?: never;
    };
    "/users/{id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Menyetel ulang kata sandi kurir */
        post: operations["resetUserPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daftar produk depot */
        get: operations["listProducts"];
        put?: never;
        /** Menambah produk */
        post: operations["createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mengubah produk */
        patch: operations["updateProduct"];
        trace?: never;
    };
    "/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daftar atau pencarian pelanggan */
        get: operations["listCustomers"];
        put?: never;
        /** Menambah pelanggan */
        post: operations["createCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rincian pelanggan */
        get: operations["getCustomer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mengubah pelanggan */
        patch: operations["updateCustomer"];
        trace?: never;
    };
    "/customers/{id}/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mengambil link pribadi pelanggan, membuatnya bila belum ada */
        post: operations["getCustomerLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{id}/link/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Membuat link pribadi baru dan mematikan yang lama */
        post: operations["rotateCustomerLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{id}/snooze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Menunda pengingat pelanggan beberapa hari */
        post: operations["snoozeCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daftar pesanan depot */
        get: operations["listOrders"];
        put?: never;
        /** Membuat pesanan atas nama pelanggan */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rincian pesanan */
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mengonfirmasi pesanan menunggu */
        post: operations["confirmOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Menugaskan kurir */
        post: operations["assignCourier"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/dispatch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Kurir berangkat */
        post: operations["dispatchOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Membatalkan pesanan dengan alasan */
        post: operations["cancelOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/mark-paid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Menandai pesanan lunas */
        post: operations["markOrderPaid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/deliver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Menyelesaikan pengantaran, menulis buku galon, loyalitas, dan prediksi */
        post: operations["deliverOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{id}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Riwayat pesanan seorang pelanggan */
        get: operations["listCustomerOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{id}/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buku galon seorang pelanggan */
        get: operations["listCustomerLedger"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{id}/ledger-adjustments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Penyesuaian manual buku galon */
        post: operations["adjustCustomerLedger"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gallons/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Total galon dipinjam dan daftar galon mengendap */
        get: operations["gallonSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courier/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Antrean antar kurir yang sedang masuk, terurut */
        get: operations["courierQueue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courier/customers/{id}/location": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Menyimpan koordinat pelanggan dari HP kurir */
        post: operations["saveCustomerLocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/depots/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Halaman publik depot, di-cache 30 detik dengan ETag */
        get: operations["publicDepot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/depots/{slug}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pesanan dari halaman publik, berstatus menunggu konfirmasi */
        post: operations["publicOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/track/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pelacakan satu pesanan */
        get: operations["trackOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/track/{token}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pelanggan membatalkan pesanan yang masih menunggu */
        post: operations["cancelTrackedOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/me/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Halaman pribadi pelanggan */
        get: operations["personalPage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/me/{token}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pesan ulang satu ketukan dari link pribadi */
        post: operations["reorder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Readiness: {
            /** @enum {string} */
            status: "ok";
            /** @enum {string} */
            database: "ok";
        };
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        ErrorBody: {
            /** @enum {string} */
            code: "validation_failed" | "unauthenticated" | "forbidden" | "not_found" | "conflict" | "invalid_transition" | "rate_limited" | "internal" | "unavailable";
            message: string;
            fields?: {
                [key: string]: string;
            };
        };
        Cursor: {
            next_cursor?: string | null;
        };
        FlagResponse: {
            data: {
                [key: string]: boolean;
            };
        };
        RegisterRequest: {
            depot_name: string;
            name: string;
            phone: string;
            password: string;
        };
        LoginRequest: {
            phone: string;
            password: string;
        };
        ChangePasswordRequest: {
            current_password: string;
            new_password: string;
        };
        /** @enum {string} */
        Role: "owner" | "courier";
        User: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            depot_id: string;
            role: components["schemas"]["Role"];
            name: string;
            phone: string;
            is_active: boolean;
            /** Format: date-time */
            last_login_at: string | null;
            /** Format: date-time */
            created_at: string;
        };
        UserResponse: {
            data: components["schemas"]["User"];
        };
        CreateCourierRequest: {
            name: string;
            phone: string;
            password: string;
        };
        UserUpdate: {
            name?: string;
            is_active?: boolean;
        };
        Depot: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            phone: string;
            address: string;
            lat: number | null;
            lng: number | null;
            timezone: string;
            /** @description Format HH:MM */
            open_time: string;
            /** @description Format HH:MM */
            close_time: string;
            delivery_fee: number;
            is_accepting_orders: boolean;
            auto_confirm_known: boolean;
            loyalty_every: number | null;
            reminder_lead_days: number;
            default_days_per_gallon: number;
            is_demo: boolean;
        };
        DepotResponse: {
            data: components["schemas"]["Depot"];
        };
        DepotUpdate: {
            name?: string;
            phone?: string;
            address?: string;
            lat?: number;
            lng?: number;
            open_time?: string;
            close_time?: string;
            delivery_fee?: number;
            is_accepting_orders?: boolean;
            auto_confirm_known?: boolean;
            /** @description 0 mematikan loyalitas */
            loyalty_every?: number;
            reminder_lead_days?: number;
            default_days_per_gallon?: number;
        };
        /** @enum {string} */
        ProductKind: "refill" | "new_gallon" | "other";
        Product: {
            /** Format: uuid */
            id: string;
            name: string;
            kind: components["schemas"]["ProductKind"];
            price: number;
            is_active: boolean;
            sort_order: number;
            /** Format: date-time */
            created_at: string;
        };
        ProductResponse: {
            data: components["schemas"]["Product"];
        };
        ProductCreate: {
            name: string;
            kind: components["schemas"]["ProductKind"];
            price: number;
            sort_order?: number;
        };
        ProductUpdate: {
            name?: string;
            kind?: components["schemas"]["ProductKind"];
            price?: number;
            is_active?: boolean;
            sort_order?: number;
        };
        /** @enum {string} */
        Confidence: "none" | "low" | "medium" | "high";
        Customer: {
            /** Format: uuid */
            id: string;
            name: string;
            phone: string;
            address: string;
            address_note: string;
            area: string;
            lat: number | null;
            lng: number | null;
            /** @enum {string} */
            source: "owner" | "public";
            is_verified: boolean;
            usual_qty: number;
            loan_balance: number;
            stamp_count: number;
            days_per_gallon: number | null;
            prediction_samples: number;
            prediction_confidence: components["schemas"]["Confidence"];
            /** Format: date-time */
            last_delivered_at: string | null;
            last_delivered_qty: number | null;
            /** Format: date-time */
            predicted_empty_at: string | null;
            /** Format: date */
            reminder_snoozed_until: string | null;
            is_active: boolean;
            has_link: boolean;
            /** Format: date-time */
            created_at: string;
        };
        CustomerResponse: {
            data: components["schemas"]["Customer"];
        };
        CustomerListResponse: {
            data: components["schemas"]["Customer"][];
            meta: components["schemas"]["Cursor"];
        };
        CustomerCreate: {
            name: string;
            phone: string;
            address?: string;
            address_note?: string;
            area?: string;
            lat?: number;
            lng?: number;
            usual_qty?: number;
        };
        CustomerUpdate: {
            name?: string;
            phone?: string;
            address?: string;
            address_note?: string;
            area?: string;
            lat?: number;
            lng?: number;
            usual_qty?: number;
            is_active?: boolean;
        };
        LinkResponse: {
            data: {
                /** Format: uri */
                link: string;
                /** Format: uri */
                wa_url: string;
            };
        };
        /** @enum {string} */
        OrderStatus: "pending" | "confirmed" | "on_delivery" | "delivered" | "cancelled";
        /** @enum {string} */
        OrderSource: "public" | "link" | "reminder" | "owner" | "courier";
        /** @enum {string} */
        Fulfilment: "delivery" | "pickup";
        /** @enum {string} */
        PaymentMethod: "cash" | "transfer" | "qris";
        OrderItem: {
            /** Format: uuid */
            product_id: string;
            product_name: string;
            product_kind: components["schemas"]["ProductKind"];
            unit_price: number;
            qty: number;
            line_total: number;
        };
        Order: {
            /** Format: uuid */
            id: string;
            code: string;
            source: components["schemas"]["OrderSource"];
            status: components["schemas"]["OrderStatus"];
            fulfilment: components["schemas"]["Fulfilment"];
            /** Format: date */
            scheduled_date: string;
            /** Format: uuid */
            customer_id: string;
            delivery_name: string;
            delivery_phone: string;
            delivery_address: string;
            delivery_note: string;
            note: string;
            refill_qty: number;
            free_qty: number;
            subtotal: number;
            delivery_fee: number;
            discount: number;
            total: number;
            payment_method: components["schemas"]["PaymentMethod"] | null;
            /** @enum {string} */
            payment_status: "unpaid" | "paid";
            /** Format: date-time */
            paid_at: string | null;
            /** Format: uuid */
            courier_id: string | null;
            courier_name: string | null;
            gallons_returned: number | null;
            /** Format: uuid */
            reminder_id: string | null;
            items: components["schemas"]["OrderItem"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            confirmed_at: string | null;
            /** Format: date-time */
            dispatched_at: string | null;
            /** Format: date-time */
            delivered_at: string | null;
            /** Format: date-time */
            cancelled_at: string | null;
            cancel_reason: string | null;
        };
        CourierOrder: {
            /** Format: uuid */
            id: string;
            code: string;
            status: components["schemas"]["OrderStatus"];
            fulfilment: components["schemas"]["Fulfilment"];
            /** Format: date */
            scheduled_date: string;
            /** Format: uuid */
            customer_id: string;
            delivery_name: string;
            delivery_phone: string;
            delivery_address: string;
            delivery_note: string;
            note: string;
            refill_qty: number;
            free_qty: number;
            total: number;
            /** @enum {string} */
            payment_status: "unpaid" | "paid";
            payment_method: components["schemas"]["PaymentMethod"] | null;
            gallons_returned: number | null;
            items: components["schemas"]["OrderItem"][];
            lat: number | null;
            lng: number | null;
            area: string;
            loan_balance: number;
            /** Format: date-time */
            dispatched_at: string | null;
            /** Format: date-time */
            created_at: string;
        };
        OrderResponse: {
            data: components["schemas"]["Order"];
        };
        OrderListResponse: {
            data: components["schemas"]["Order"][];
            meta: components["schemas"]["Cursor"];
        };
        OrderCreate: {
            /** Format: uuid */
            customer_id: string;
            items?: {
                /** Format: uuid */
                product_id: string;
                qty: number;
            }[];
            /** @description Dipakai bila items kosong, bawaan jumlah biasa pelanggan */
            refill_qty?: number;
            fulfilment?: components["schemas"]["Fulfilment"];
            /** Format: date */
            scheduled_date?: string;
            note?: string;
        };
        LedgerEntry: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            order_id: string | null;
            /** @enum {string} */
            kind: "delivery" | "adjustment" | "lost";
            delta: number;
            balance_after: number;
            note: string;
            /** Format: date-time */
            created_at: string;
        };
        GallonSummary: {
            total_on_loan: number;
            customers_with_loan: number;
            idle: components["schemas"]["Customer"][];
        };
        PublicDepot: {
            name: string;
            slug: string;
            phone: string;
            address: string;
            open_time: string;
            close_time: string;
            delivery_fee: number;
            is_accepting_orders: boolean;
        };
        PublicDepotPage: {
            depot: components["schemas"]["PublicDepot"];
            products: components["schemas"]["Product"][];
        };
        PublicOrderCreate: {
            name: string;
            phone: string;
            address: string;
            address_note?: string;
            qty: number;
            note?: string;
            /** @description Bidang jebakan untuk bot, harus kosong */
            website?: string;
        };
        CreatedOrder: {
            code: string;
            status: components["schemas"]["OrderStatus"];
            track_token: string;
        };
        TrackedOrder: {
            code: string;
            status: components["schemas"]["OrderStatus"];
            fulfilment: components["schemas"]["Fulfilment"];
            /** Format: date */
            scheduled_date: string;
            delivery_name: string;
            /** @description Disamarkan, hanya 4 digit terakhir */
            delivery_phone: string;
            delivery_address: string;
            refill_qty: number;
            free_qty: number;
            total: number;
            /** @enum {string} */
            payment_status: "unpaid" | "paid";
            items: components["schemas"]["OrderItem"][];
            can_cancel: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            confirmed_at: string | null;
            /** Format: date-time */
            dispatched_at: string | null;
            /** Format: date-time */
            delivered_at: string | null;
            /** Format: date-time */
            cancelled_at: string | null;
            depot: components["schemas"]["PublicDepot"];
        };
        PersonalPage: {
            customer: {
                name: string;
                phone_masked: string;
                usual_qty: number;
                loan_balance: number;
                stamp_count: number;
                area: string;
            };
            depot: components["schemas"]["PublicDepot"] & {
                refill_price: number;
                loyalty_every: number | null;
            };
            active_orders: components["schemas"]["TrackedOrder"][];
            recent_orders: components["schemas"]["TrackedOrder"][];
        };
        SessionResponse: {
            data: {
                user: components["schemas"]["User"];
                depot: components["schemas"]["Depot"];
            };
        };
    };
    responses: {
        /** @description Kode dan token pelacakan pesanan */
        CreatedOrder: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    data: components["schemas"]["CreatedOrder"];
                };
            };
        };
        /** @description Pesanan yang dilacak */
        Track: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    data: components["schemas"]["TrackedOrder"];
                };
            };
        };
        /** @description Pesanan */
        Order: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["OrderResponse"];
            };
        };
        /** @description Galat baku */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        Token: string;
        IdempotencyKey: string;
        Cursor: string;
        Limit: number;
        Id: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Siap */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Readiness"];
                    };
                };
            };
            503: components["responses"]["Error"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Depot dibuat dan sesi dipasang di cookie */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            422: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Berhasil masuk */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            401: components["responses"]["Error"];
            409: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesi diperbarui */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlagResponse"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Keluar */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlagResponse"];
                };
            };
        };
    };
    logoutAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Keluar */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlagResponse"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesi aktif */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Kata sandi diganti */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlagResponse"];
                };
            };
            401: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    getDepot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Depot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepotResponse"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    updateDepot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepotUpdate"];
            };
        };
        responses: {
            /** @description Depot diperbarui */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepotResponse"];
                };
            };
            422: components["responses"]["Error"];
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar pengguna */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["User"][];
                    };
                };
            };
        };
    };
    createCourier: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCourierRequest"];
            };
        };
        responses: {
            /** @description Kurir dibuat */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            422: components["responses"]["Error"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Pengguna diperbarui */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            404: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    resetUserPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    password: string;
                };
            };
        };
        responses: {
            /** @description Kata sandi disetel ulang */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlagResponse"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    listProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar produk */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Product"][];
                    };
                };
            };
        };
    };
    createProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreate"];
            };
        };
        responses: {
            /** @description Produk dibuat */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponse"];
                };
            };
            422: components["responses"]["Error"];
        };
    };
    updateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductUpdate"];
            };
        };
        responses: {
            /** @description Produk diperbarui */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponse"];
                };
            };
            404: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    listCustomers: {
        parameters: {
            query?: {
                q?: string;
                filter?: "all" | "due" | "at_risk" | "loan";
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar pelanggan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerListResponse"];
                };
            };
        };
    };
    createCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerCreate"];
            };
        };
        responses: {
            /** @description Pelanggan dibuat */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerResponse"];
                };
            };
            422: components["responses"]["Error"];
        };
    };
    getCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pelanggan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerResponse"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    updateCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerUpdate"];
            };
        };
        responses: {
            /** @description Pelanggan diperbarui */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerResponse"];
                };
            };
            404: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    getCustomerLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Link pribadi */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkResponse"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    rotateCustomerLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Link baru */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkResponse"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    snoozeCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    days: number;
                };
            };
        };
        responses: {
            /** @description Ditunda */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** Format: date */
                            snoozed_until: string;
                        };
                    };
                };
            };
            404: components["responses"]["Error"];
        };
    };
    listOrders: {
        parameters: {
            query?: {
                status?: components["schemas"]["OrderStatus"];
                date?: string;
                courier_id?: string;
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar pesanan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderListResponse"];
                };
            };
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCreate"];
            };
        };
        responses: {
            /** @description Pesanan yang sama sudah dibuat sebelumnya dengan Idempotency-Key ini */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            /** @description Pesanan dibuat */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            422: components["responses"]["Error"];
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pesanan, pemilik menerima Order dan kurir menerima CourierOrder */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    confirmOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Order"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    assignCourier: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    courier_id: string;
                };
            };
        };
        responses: {
            200: components["responses"]["Order"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    dispatchOrder: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Order"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    cancelOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    reason: string;
                };
            };
        };
        responses: {
            200: components["responses"]["Order"];
            409: components["responses"]["Error"];
        };
    };
    markOrderPaid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    payment_method?: components["schemas"]["PaymentMethod"];
                };
            };
        };
        responses: {
            200: components["responses"]["Order"];
            409: components["responses"]["Error"];
        };
    };
    deliverOrder: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    gallons_returned: number;
                    payment_method?: components["schemas"]["PaymentMethod"];
                    paid?: boolean;
                };
            };
        };
        responses: {
            200: components["responses"]["Order"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    listCustomerOrders: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar pesanan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderListResponse"];
                };
            };
        };
    };
    listCustomerLedger: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Buku galon */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["LedgerEntry"][];
                        meta: components["schemas"]["Cursor"];
                    };
                };
            };
            404: components["responses"]["Error"];
        };
    };
    adjustCustomerLedger: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    kind: "adjustment" | "lost";
                    /** @description Positif menambah galon di pelanggan, negatif mengurangi */
                    delta: number;
                    note: string;
                };
            };
        };
        responses: {
            /** @description Catatan ditambahkan */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["LedgerEntry"];
                    };
                };
            };
            404: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    gallonSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ringkasan galon */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["GallonSummary"];
                    };
                };
            };
        };
    };
    courierQueue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Antrean */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CourierOrder"][];
                    };
                };
            };
        };
    };
    saveCustomerLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    lat: number;
                    lng: number;
                };
            };
        };
        responses: {
            /** @description Tersimpan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlagResponse"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    publicDepot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Depot dan produk aktif */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PublicDepotPage"];
                    };
                };
            };
            /** @description Tidak berubah */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
    publicOrder: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicOrderCreate"];
            };
        };
        responses: {
            200: components["responses"]["CreatedOrder"];
            201: components["responses"]["CreatedOrder"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    trackOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: components["parameters"]["Token"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Track"];
            404: components["responses"]["Error"];
        };
    };
    cancelTrackedOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: components["parameters"]["Token"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Track"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    personalPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: components["parameters"]["Token"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ringkasan pelanggan, pesanan aktif, lima riwayat terakhir */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PersonalPage"];
                    };
                };
            };
            404: components["responses"]["Error"];
        };
    };
    reorder: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                token: components["parameters"]["Token"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    qty?: number;
                    /**
                     * Format: date
                     * @description Hari ini atau besok
                     */
                    scheduled_date?: string;
                    note?: string;
                    /**
                     * Format: uuid
                     * @description ID pengingat dari link di pesan WhatsApp
                     */
                    r?: string;
                };
            };
        };
        responses: {
            200: components["responses"]["CreatedOrder"];
            201: components["responses"]["CreatedOrder"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
}
