/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Memeriksa kesiapan API dan basis data */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Readiness: {
            /** @enum {string} */
            status: "ok";
            /** @enum {string} */
            database: "ok";
        };
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        ErrorBody: {
            /** @enum {string} */
            code: "validation_failed" | "unauthenticated" | "forbidden" | "not_found" | "conflict" | "invalid_transition" | "rate_limited" | "internal" | "unavailable";
            message: string;
            fields?: {
                [key: string]: string;
            };
        };
        Cursor: {
            next_cursor?: string | null;
        };
    };
    responses: {
        /** @description Galat baku */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Siap */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Readiness"];
                    };
                };
            };
            503: components["responses"]["Error"];
        };
    };
}
