// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countCustomers = `-- name: CountCustomers :one
SELECT count(*) FROM customers WHERE depot_id = $1 AND is_active
`

func (q *Queries) CountCustomers(ctx context.Context, depotID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomers, depotID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (id, depot_id, name, phone, address, address_note, area, lat, lng, source, is_verified, usual_qty)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, depot_id, name, phone, address, address_note, area, lat, lng, token_hash, token_enc, token_rotated_at, source, is_verified, usual_qty, loan_balance, stamp_count, days_per_gallon, prediction_samples, prediction_confidence, last_delivered_at, last_delivered_qty, predicted_empty_at, reminder_snoozed_until, is_active, created_at, updated_at
`

type CreateCustomerParams struct {
	ID          uuid.UUID
	DepotID     uuid.UUID
	Name        string
	Phone       string
	Address     string
	AddressNote string
	Area        string
	Lat         *float64
	Lng         *float64
	Source      string
	IsVerified  bool
	UsualQty    int32
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.ID,
		arg.DepotID,
		arg.Name,
		arg.Phone,
		arg.Address,
		arg.AddressNote,
		arg.Area,
		arg.Lat,
		arg.Lng,
		arg.Source,
		arg.IsVerified,
		arg.UsualQty,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.DepotID,
		&i.Name,
		&i.Phone,
		&i.Address,
		&i.AddressNote,
		&i.Area,
		&i.Lat,
		&i.Lng,
		&i.TokenHash,
		&i.TokenEnc,
		&i.TokenRotatedAt,
		&i.Source,
		&i.IsVerified,
		&i.UsualQty,
		&i.LoanBalance,
		&i.StampCount,
		&i.DaysPerGallon,
		&i.PredictionSamples,
		&i.PredictionConfidence,
		&i.LastDeliveredAt,
		&i.LastDeliveredQty,
		&i.PredictedEmptyAt,
		&i.ReminderSnoozedUntil,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, depot_id, name, phone, address, address_note, area, lat, lng, token_hash, token_enc, token_rotated_at, source, is_verified, usual_qty, loan_balance, stamp_count, days_per_gallon, prediction_samples, prediction_confidence, last_delivered_at, last_delivered_qty, predicted_empty_at, reminder_snoozed_until, is_active, created_at, updated_at FROM customers WHERE id = $1 AND depot_id = $2
`

type GetCustomerParams struct {
	ID      uuid.UUID
	DepotID uuid.UUID
}

func (q *Queries) GetCustomer(ctx context.Context, arg GetCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomer, arg.ID, arg.DepotID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.DepotID,
		&i.Name,
		&i.Phone,
		&i.Address,
		&i.AddressNote,
		&i.Area,
		&i.Lat,
		&i.Lng,
		&i.TokenHash,
		&i.TokenEnc,
		&i.TokenRotatedAt,
		&i.Source,
		&i.IsVerified,
		&i.UsualQty,
		&i.LoanBalance,
		&i.StampCount,
		&i.DaysPerGallon,
		&i.PredictionSamples,
		&i.PredictionConfidence,
		&i.LastDeliveredAt,
		&i.LastDeliveredQty,
		&i.PredictedEmptyAt,
		&i.ReminderSnoozedUntil,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByPhone = `-- name: GetCustomerByPhone :one
SELECT id, depot_id, name, phone, address, address_note, area, lat, lng, token_hash, token_enc, token_rotated_at, source, is_verified, usual_qty, loan_balance, stamp_count, days_per_gallon, prediction_samples, prediction_confidence, last_delivered_at, last_delivered_qty, predicted_empty_at, reminder_snoozed_until, is_active, created_at, updated_at FROM customers WHERE depot_id = $1 AND phone = $2
`

type GetCustomerByPhoneParams struct {
	DepotID uuid.UUID
	Phone   string
}

func (q *Queries) GetCustomerByPhone(ctx context.Context, arg GetCustomerByPhoneParams) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByPhone, arg.DepotID, arg.Phone)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.DepotID,
		&i.Name,
		&i.Phone,
		&i.Address,
		&i.AddressNote,
		&i.Area,
		&i.Lat,
		&i.Lng,
		&i.TokenHash,
		&i.TokenEnc,
		&i.TokenRotatedAt,
		&i.Source,
		&i.IsVerified,
		&i.UsualQty,
		&i.LoanBalance,
		&i.StampCount,
		&i.DaysPerGallon,
		&i.PredictionSamples,
		&i.PredictionConfidence,
		&i.LastDeliveredAt,
		&i.LastDeliveredQty,
		&i.PredictedEmptyAt,
		&i.ReminderSnoozedUntil,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByTokenHash = `-- name: GetCustomerByTokenHash :one
SELECT id, depot_id, name, phone, address, address_note, area, lat, lng, token_hash, token_enc, token_rotated_at, source, is_verified, usual_qty, loan_balance, stamp_count, days_per_gallon, prediction_samples, prediction_confidence, last_delivered_at, last_delivered_qty, predicted_empty_at, reminder_snoozed_until, is_active, created_at, updated_at FROM customers WHERE token_hash = $1 AND is_active
`

func (q *Queries) GetCustomerByTokenHash(ctx context.Context, tokenHash []byte) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByTokenHash, tokenHash)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.DepotID,
		&i.Name,
		&i.Phone,
		&i.Address,
		&i.AddressNote,
		&i.Area,
		&i.Lat,
		&i.Lng,
		&i.TokenHash,
		&i.TokenEnc,
		&i.TokenRotatedAt,
		&i.Source,
		&i.IsVerified,
		&i.UsualQty,
		&i.LoanBalance,
		&i.StampCount,
		&i.DaysPerGallon,
		&i.PredictionSamples,
		&i.PredictionConfidence,
		&i.LastDeliveredAt,
		&i.LastDeliveredQty,
		&i.PredictedEmptyAt,
		&i.ReminderSnoozedUntil,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerForUpdate = `-- name: GetCustomerForUpdate :one
SELECT id, depot_id, name, phone, address, address_note, area, lat, lng, token_hash, token_enc, token_rotated_at, source, is_verified, usual_qty, loan_balance, stamp_count, days_per_gallon, prediction_samples, prediction_confidence, last_delivered_at, last_delivered_qty, predicted_empty_at, reminder_snoozed_until, is_active, created_at, updated_at FROM customers WHERE id = $1 AND depot_id = $2 FOR UPDATE
`

type GetCustomerForUpdateParams struct {
	ID      uuid.UUID
	DepotID uuid.UUID
}

func (q *Queries) GetCustomerForUpdate(ctx context.Context, arg GetCustomerForUpdateParams) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerForUpdate, arg.ID, arg.DepotID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.DepotID,
		&i.Name,
		&i.Phone,
		&i.Address,
		&i.AddressNote,
		&i.Area,
		&i.Lat,
		&i.Lng,
		&i.TokenHash,
		&i.TokenEnc,
		&i.TokenRotatedAt,
		&i.Source,
		&i.IsVerified,
		&i.UsualQty,
		&i.LoanBalance,
		&i.StampCount,
		&i.DaysPerGallon,
		&i.PredictionSamples,
		&i.PredictionConfidence,
		&i.LastDeliveredAt,
		&i.LastDeliveredQty,
		&i.PredictedEmptyAt,
		&i.ReminderSnoozedUntil,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAtRiskCustomers = `-- name: ListAtRiskCustomers :many
SELECT customers.id, customers.depot_id, customers.name, customers.phone, customers.address, customers.address_note, customers.area, customers.lat, customers.lng, customers.token_hash, customers.token_enc, customers.token_rotated_at, customers.source, customers.is_verified, customers.usual_qty, customers.loan_balance, customers.stamp_count, customers.days_per_gallon, customers.prediction_samples, customers.prediction_confidence, customers.last_delivered_at, customers.last_delivered_qty, customers.predicted_empty_at, customers.reminder_snoozed_until, customers.is_active, customers.created_at, customers.updated_at FROM customers
WHERE customers.depot_id = $1 AND is_active AND is_verified
  AND last_delivered_at IS NOT NULL AND days_per_gallon IS NOT NULL AND last_delivered_qty IS NOT NULL
  AND $3::timestamptz > last_delivered_at + (2 * last_delivered_qty * days_per_gallon) * interval '1 day'
  AND NOT EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = customers.id AND o.status IN ('pending', 'confirmed', 'on_delivery'))
ORDER BY last_delivered_at, id
LIMIT $2
`

type ListAtRiskCustomersParams struct {
	DepotID uuid.UUID
	Limit   int32
	Now     time.Time
}

func (q *Queries) ListAtRiskCustomers(ctx context.Context, arg ListAtRiskCustomersParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listAtRiskCustomers, arg.DepotID, arg.Limit, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.DepotID,
			&i.Name,
			&i.Phone,
			&i.Address,
			&i.AddressNote,
			&i.Area,
			&i.Lat,
			&i.Lng,
			&i.TokenHash,
			&i.TokenEnc,
			&i.TokenRotatedAt,
			&i.Source,
			&i.IsVerified,
			&i.UsualQty,
			&i.LoanBalance,
			&i.StampCount,
			&i.DaysPerGallon,
			&i.PredictionSamples,
			&i.PredictionConfidence,
			&i.LastDeliveredAt,
			&i.LastDeliveredQty,
			&i.PredictedEmptyAt,
			&i.ReminderSnoozedUntil,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, depot_id, name, phone, address, address_note, area, lat, lng, token_hash, token_enc, token_rotated_at, source, is_verified, usual_qty, loan_balance, stamp_count, days_per_gallon, prediction_samples, prediction_confidence, last_delivered_at, last_delivered_qty, predicted_empty_at, reminder_snoozed_until, is_active, created_at, updated_at FROM customers
WHERE depot_id = $1
  AND ($3::timestamptz IS NULL OR (created_at, id) < ($3::timestamptz, $4::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListCustomersParams struct {
	DepotID  uuid.UUID
	Limit    int32
	BeforeAt *time.Time
	BeforeID *uuid.UUID
}

func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers,
		arg.DepotID,
		arg.Limit,
		arg.BeforeAt,
		arg.BeforeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.DepotID,
			&i.Name,
			&i.Phone,
			&i.Address,
			&i.AddressNote,
			&i.Area,
			&i.Lat,
			&i.Lng,
			&i.TokenHash,
			&i.TokenEnc,
			&i.TokenRotatedAt,
			&i.Source,
			&i.IsVerified,
			&i.UsualQty,
			&i.LoanBalance,
			&i.StampCount,
			&i.DaysPerGallon,
			&i.PredictionSamples,
			&i.PredictionConfidence,
			&i.LastDeliveredAt,
			&i.LastDeliveredQty,
			&i.PredictedEmptyAt,
			&i.ReminderSnoozedUntil,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueCustomers = `-- name: ListDueCustomers :many
SELECT customers.id, customers.depot_id, customers.name, customers.phone, customers.address, customers.address_note, customers.area, customers.lat, customers.lng, customers.token_hash, customers.token_enc, customers.token_rotated_at, customers.source, customers.is_verified, customers.usual_qty, customers.loan_balance, customers.stamp_count, customers.days_per_gallon, customers.prediction_samples, customers.prediction_confidence, customers.last_delivered_at, customers.last_delivered_qty, customers.predicted_empty_at, customers.reminder_snoozed_until, customers.is_active, customers.created_at, customers.updated_at FROM customers
WHERE customers.depot_id = $1 AND is_active AND is_verified
  AND predicted_empty_at IS NOT NULL AND predicted_empty_at <= $3::timestamptz
  AND NOT EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = customers.id AND o.status IN ('pending', 'confirmed', 'on_delivery'))
ORDER BY predicted_empty_at, id
LIMIT $2
`

type ListDueCustomersParams struct {
	DepotID   uuid.UUID
	Limit     int32
	DueBefore time.Time
}

func (q *Queries) ListDueCustomers(ctx context.Context, arg ListDueCustomersParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listDueCustomers, arg.DepotID, arg.Limit, arg.DueBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.DepotID,
			&i.Name,
			&i.Phone,
			&i.Address,
			&i.AddressNote,
			&i.Area,
			&i.Lat,
			&i.Lng,
			&i.TokenHash,
			&i.TokenEnc,
			&i.TokenRotatedAt,
			&i.Source,
			&i.IsVerified,
			&i.UsualQty,
			&i.LoanBalance,
			&i.StampCount,
			&i.DaysPerGallon,
			&i.PredictionSamples,
			&i.PredictionConfidence,
			&i.LastDeliveredAt,
			&i.LastDeliveredQty,
			&i.PredictedEmptyAt,
			&i.ReminderSnoozedUntil,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdleLoanCustomers = `-- name: ListIdleLoanCustomers :many
SELECT id, depot_id, name, phone, address, address_note, area, lat, lng, token_hash, token_enc, token_rotated_at, source, is_verified, usual_qty, loan_balance, stamp_count, days_per_gallon, prediction_samples, prediction_confidence, last_delivered_at, last_delivered_qty, predicted_empty_at, reminder_snoozed_until, is_active, created_at, updated_at FROM customers
WHERE depot_id = $1 AND loan_balance > 0
  AND (last_delivered_at IS NULL OR last_delivered_at < $3::timestamptz)
ORDER BY loan_balance DESC, last_delivered_at NULLS FIRST, id
LIMIT $2
`

type ListIdleLoanCustomersParams struct {
	DepotID    uuid.UUID
	Limit      int32
	IdleBefore time.Time
}

func (q *Queries) ListIdleLoanCustomers(ctx context.Context, arg ListIdleLoanCustomersParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listIdleLoanCustomers, arg.DepotID, arg.Limit, arg.IdleBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.DepotID,
			&i.Name,
			&i.Phone,
			&i.Address,
			&i.AddressNote,
			&i.Area,
			&i.Lat,
			&i.Lng,
			&i.TokenHash,
			&i.TokenEnc,
			&i.TokenRotatedAt,
			&i.Source,
			&i.IsVerified,
			&i.UsualQty,
			&i.LoanBalance,
			&i.StampCount,
			&i.DaysPerGallon,
			&i.PredictionSamples,
			&i.PredictionConfidence,
			&i.LastDeliveredAt,
			&i.LastDeliveredQty,
			&i.PredictedEmptyAt,
			&i.ReminderSnoozedUntil,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoanCustomers = `-- name: ListLoanCustomers :many
SELECT id, depot_id, name, phone, address, address_note, area, lat, lng, token_hash, token_enc, token_rotated_at, source, is_verified, usual_qty, loan_balance, stamp_count, days_per_gallon, prediction_samples, prediction_confidence, last_delivered_at, last_delivered_qty, predicted_empty_at, reminder_snoozed_until, is_active, created_at, updated_at FROM customers
WHERE depot_id = $1 AND loan_balance > 0
ORDER BY loan_balance DESC, last_delivered_at NULLS FIRST, id
LIMIT $2
`

type ListLoanCustomersParams struct {
	DepotID uuid.UUID
	Limit   int32
}

func (q *Queries) ListLoanCustomers(ctx context.Context, arg ListLoanCustomersParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listLoanCustomers, arg.DepotID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.DepotID,
			&i.Name,
			&i.Phone,
			&i.Address,
			&i.AddressNote,
			&i.Area,
			&i.Lat,
			&i.Lng,
			&i.TokenHash,
			&i.TokenEnc,
			&i.TokenRotatedAt,
			&i.Source,
			&i.IsVerified,
			&i.UsualQty,
			&i.LoanBalance,
			&i.StampCount,
			&i.DaysPerGallon,
			&i.PredictionSamples,
			&i.PredictionConfidence,
			&i.LastDeliveredAt,
			&i.LastDeliveredQty,
			&i.PredictedEmptyAt,
			&i.ReminderSnoozedUntil,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCustomers = `-- name: SearchCustomers :many
SELECT id, depot_id, name, phone, address, address_note, area, lat, lng, token_hash, token_enc, token_rotated_at, source, is_verified, usual_qty, loan_balance, stamp_count, days_per_gallon, prediction_samples, prediction_confidence, last_delivered_at, last_delivered_qty, predicted_empty_at, reminder_snoozed_until, is_active, created_at, updated_at FROM customers
WHERE depot_id = $1
  AND (name ILIKE '%' || $3::text || '%'
       OR phone ILIKE '%' || $3::text || '%'
       OR address ILIKE '%' || $3::text || '%')
ORDER BY is_active DESC, name
LIMIT $2
`

type SearchCustomersParams struct {
	DepotID uuid.UUID
	Limit   int32
	Q       string
}

func (q *Queries) SearchCustomers(ctx context.Context, arg SearchCustomersParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, searchCustomers, arg.DepotID, arg.Limit, arg.Q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.DepotID,
			&i.Name,
			&i.Phone,
			&i.Address,
			&i.AddressNote,
			&i.Area,
			&i.Lat,
			&i.Lng,
			&i.TokenHash,
			&i.TokenEnc,
			&i.TokenRotatedAt,
			&i.Source,
			&i.IsVerified,
			&i.UsualQty,
			&i.LoanBalance,
			&i.StampCount,
			&i.DaysPerGallon,
			&i.PredictionSamples,
			&i.PredictionConfidence,
			&i.LastDeliveredAt,
			&i.LastDeliveredQty,
			&i.PredictedEmptyAt,
			&i.ReminderSnoozedUntil,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCustomerLocation = `-- name: SetCustomerLocation :execrows
UPDATE customers SET lat = $3, lng = $4, updated_at = now() WHERE id = $1 AND depot_id = $2
`

type SetCustomerLocationParams struct {
	ID      uuid.UUID
	DepotID uuid.UUID
	Lat     *float64
	Lng     *float64
}

func (q *Queries) SetCustomerLocation(ctx context.Context, arg SetCustomerLocationParams) (int64, error) {
	result, err := q.db.Exec(ctx, setCustomerLocation,
		arg.ID,
		arg.DepotID,
		arg.Lat,
		arg.Lng,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setCustomerToken = `-- name: SetCustomerToken :execrows
UPDATE customers SET token_hash = $3, token_enc = $4, token_rotated_at = $5, updated_at = now()
WHERE id = $1 AND depot_id = $2
`

type SetCustomerTokenParams struct {
	ID             uuid.UUID
	DepotID        uuid.UUID
	TokenHash      []byte
	TokenEnc       []byte
	TokenRotatedAt *time.Time
}

func (q *Queries) SetCustomerToken(ctx context.Context, arg SetCustomerTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, setCustomerToken,
		arg.ID,
		arg.DepotID,
		arg.TokenHash,
		arg.TokenEnc,
		arg.TokenRotatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const snoozeCustomer = `-- name: SnoozeCustomer :execrows
UPDATE customers SET reminder_snoozed_until = $3, updated_at = now() WHERE id = $1 AND depot_id = $2
`

type SnoozeCustomerParams struct {
	ID                   uuid.UUID
	DepotID              uuid.UUID
	ReminderSnoozedUntil *time.Time
}

func (q *Queries) SnoozeCustomer(ctx context.Context, arg SnoozeCustomerParams) (int64, error) {
	result, err := q.db.Exec(ctx, snoozeCustomer, arg.ID, arg.DepotID, arg.ReminderSnoozedUntil)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sumLoanBalance = `-- name: SumLoanBalance :one
SELECT coalesce(sum(loan_balance), 0)::bigint FROM customers WHERE depot_id = $1
`

func (q *Queries) SumLoanBalance(ctx context.Context, depotID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumLoanBalance, depotID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers
SET name = COALESCE($3, name),
    phone = COALESCE($4, phone),
    address = COALESCE($5, address),
    address_note = COALESCE($6, address_note),
    area = COALESCE($7, area),
    lat = COALESCE($8, lat),
    lng = COALESCE($9, lng),
    usual_qty = COALESCE($10, usual_qty),
    is_active = COALESCE($11, is_active),
    updated_at = now()
WHERE id = $1 AND depot_id = $2
RETURNING id, depot_id, name, phone, address, address_note, area, lat, lng, token_hash, token_enc, token_rotated_at, source, is_verified, usual_qty, loan_balance, stamp_count, days_per_gallon, prediction_samples, prediction_confidence, last_delivered_at, last_delivered_qty, predicted_empty_at, reminder_snoozed_until, is_active, created_at, updated_at
`

type UpdateCustomerParams struct {
	ID          uuid.UUID
	DepotID     uuid.UUID
	Name        *string
	Phone       *string
	Address     *string
	AddressNote *string
	Area        *string
	Lat         *float64
	Lng         *float64
	UsualQty    *int32
	IsActive    *bool
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.ID,
		arg.DepotID,
		arg.Name,
		arg.Phone,
		arg.Address,
		arg.AddressNote,
		arg.Area,
		arg.Lat,
		arg.Lng,
		arg.UsualQty,
		arg.IsActive,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.DepotID,
		&i.Name,
		&i.Phone,
		&i.Address,
		&i.AddressNote,
		&i.Area,
		&i.Lat,
		&i.Lng,
		&i.TokenHash,
		&i.TokenEnc,
		&i.TokenRotatedAt,
		&i.Source,
		&i.IsVerified,
		&i.UsualQty,
		&i.LoanBalance,
		&i.StampCount,
		&i.DaysPerGallon,
		&i.PredictionSamples,
		&i.PredictionConfidence,
		&i.LastDeliveredAt,
		&i.LastDeliveredQty,
		&i.PredictedEmptyAt,
		&i.ReminderSnoozedUntil,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
