// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: demo.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const clearDepotReminderOrders = `-- name: ClearDepotReminderOrders :exec
UPDATE reminders SET order_id = NULL WHERE depot_id = $1
`

func (q *Queries) ClearDepotReminderOrders(ctx context.Context, depotID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearDepotReminderOrders, depotID)
	return err
}

const deleteDepot = `-- name: DeleteDepot :exec
DELETE FROM depots WHERE id = $1
`

func (q *Queries) DeleteDepot(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDepot, id)
	return err
}

const deleteDepotAuditLogs = `-- name: DeleteDepotAuditLogs :exec
DELETE FROM audit_logs WHERE depot_id = $1
`

func (q *Queries) DeleteDepotAuditLogs(ctx context.Context, depotID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDepotAuditLogs, depotID)
	return err
}

const deleteDepotCustomers = `-- name: DeleteDepotCustomers :exec
DELETE FROM customers WHERE depot_id = $1
`

func (q *Queries) DeleteDepotCustomers(ctx context.Context, depotID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDepotCustomers, depotID)
	return err
}

const deleteDepotLedger = `-- name: DeleteDepotLedger :exec
DELETE FROM gallon_ledger WHERE depot_id = $1
`

func (q *Queries) DeleteDepotLedger(ctx context.Context, depotID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDepotLedger, depotID)
	return err
}

const deleteDepotOrderCounters = `-- name: DeleteDepotOrderCounters :exec
DELETE FROM order_counters WHERE depot_id = $1
`

func (q *Queries) DeleteDepotOrderCounters(ctx context.Context, depotID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDepotOrderCounters, depotID)
	return err
}

const deleteDepotOrderEvents = `-- name: DeleteDepotOrderEvents :exec
DELETE FROM order_events WHERE depot_id = $1
`

func (q *Queries) DeleteDepotOrderEvents(ctx context.Context, depotID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDepotOrderEvents, depotID)
	return err
}

const deleteDepotOrderItems = `-- name: DeleteDepotOrderItems :exec
DELETE FROM order_items WHERE order_id IN (SELECT id FROM orders WHERE depot_id = $1)
`

func (q *Queries) DeleteDepotOrderItems(ctx context.Context, depotID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDepotOrderItems, depotID)
	return err
}

const deleteDepotOrders = `-- name: DeleteDepotOrders :exec
DELETE FROM orders WHERE depot_id = $1
`

func (q *Queries) DeleteDepotOrders(ctx context.Context, depotID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDepotOrders, depotID)
	return err
}

const deleteDepotProducts = `-- name: DeleteDepotProducts :exec
DELETE FROM products WHERE depot_id = $1
`

func (q *Queries) DeleteDepotProducts(ctx context.Context, depotID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDepotProducts, depotID)
	return err
}

const deleteDepotReminders = `-- name: DeleteDepotReminders :exec
DELETE FROM reminders WHERE depot_id = $1
`

func (q *Queries) DeleteDepotReminders(ctx context.Context, depotID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDepotReminders, depotID)
	return err
}

const deleteDepotSessions = `-- name: DeleteDepotSessions :exec
DELETE FROM sessions WHERE user_id IN (SELECT id FROM users WHERE depot_id = $1)
`

func (q *Queries) DeleteDepotSessions(ctx context.Context, depotID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDepotSessions, depotID)
	return err
}

const deleteDepotUsers = `-- name: DeleteDepotUsers :exec
DELETE FROM users WHERE depot_id = $1
`

func (q *Queries) DeleteDepotUsers(ctx context.Context, depotID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDepotUsers, depotID)
	return err
}

const setDepotDemo = `-- name: SetDepotDemo :exec
UPDATE depots SET is_demo = true, lat = $2, lng = $3, address = $4, loyalty_every = $5, updated_at = now() WHERE id = $1
`

type SetDepotDemoParams struct {
	ID           uuid.UUID
	Lat          *float64
	Lng          *float64
	Address      string
	LoyaltyEvery *int32
}

func (q *Queries) SetDepotDemo(ctx context.Context, arg SetDepotDemoParams) error {
	_, err := q.db.Exec(ctx, setDepotDemo,
		arg.ID,
		arg.Lat,
		arg.Lng,
		arg.Address,
		arg.LoyaltyEvery,
	)
	return err
}
