// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: depots.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createDepot = `-- name: CreateDepot :one
INSERT INTO depots (id, name, slug, phone, address)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, slug, phone, address, lat, lng, timezone, open_time, close_time, delivery_fee, is_accepting_orders, auto_confirm_known, loyalty_every, reminder_lead_days, default_days_per_gallon, is_demo, created_at, updated_at
`

type CreateDepotParams struct {
	ID      uuid.UUID
	Name    string
	Slug    string
	Phone   string
	Address string
}

func (q *Queries) CreateDepot(ctx context.Context, arg CreateDepotParams) (Depot, error) {
	row := q.db.QueryRow(ctx, createDepot,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Phone,
		arg.Address,
	)
	var i Depot
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Phone,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.Timezone,
		&i.OpenTime,
		&i.CloseTime,
		&i.DeliveryFee,
		&i.IsAcceptingOrders,
		&i.AutoConfirmKnown,
		&i.LoyaltyEvery,
		&i.ReminderLeadDays,
		&i.DefaultDaysPerGallon,
		&i.IsDemo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDepot = `-- name: GetDepot :one
SELECT id, name, slug, phone, address, lat, lng, timezone, open_time, close_time, delivery_fee, is_accepting_orders, auto_confirm_known, loyalty_every, reminder_lead_days, default_days_per_gallon, is_demo, created_at, updated_at FROM depots WHERE id = $1
`

func (q *Queries) GetDepot(ctx context.Context, id uuid.UUID) (Depot, error) {
	row := q.db.QueryRow(ctx, getDepot, id)
	var i Depot
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Phone,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.Timezone,
		&i.OpenTime,
		&i.CloseTime,
		&i.DeliveryFee,
		&i.IsAcceptingOrders,
		&i.AutoConfirmKnown,
		&i.LoyaltyEvery,
		&i.ReminderLeadDays,
		&i.DefaultDaysPerGallon,
		&i.IsDemo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDepotBySlug = `-- name: GetDepotBySlug :one
SELECT id, name, slug, phone, address, lat, lng, timezone, open_time, close_time, delivery_fee, is_accepting_orders, auto_confirm_known, loyalty_every, reminder_lead_days, default_days_per_gallon, is_demo, created_at, updated_at FROM depots WHERE slug = $1
`

func (q *Queries) GetDepotBySlug(ctx context.Context, slug string) (Depot, error) {
	row := q.db.QueryRow(ctx, getDepotBySlug, slug)
	var i Depot
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Phone,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.Timezone,
		&i.OpenTime,
		&i.CloseTime,
		&i.DeliveryFee,
		&i.IsAcceptingOrders,
		&i.AutoConfirmKnown,
		&i.LoyaltyEvery,
		&i.ReminderLeadDays,
		&i.DefaultDaysPerGallon,
		&i.IsDemo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
