// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gallon_ledger.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const applyDeliveryToCustomer = `-- name: ApplyDeliveryToCustomer :exec
UPDATE customers
SET loan_balance = $3,
    stamp_count = $4,
    days_per_gallon = $5,
    prediction_samples = $6,
    prediction_confidence = $7,
    predicted_empty_at = $8,
    last_delivered_at = $9,
    last_delivered_qty = $10,
    is_verified = true,
    updated_at = now()
WHERE id = $1 AND depot_id = $2
`

type ApplyDeliveryToCustomerParams struct {
	ID                   uuid.UUID
	DepotID              uuid.UUID
	LoanBalance          int32
	StampCount           int32
	DaysPerGallon        *float64
	PredictionSamples    int32
	PredictionConfidence string
	PredictedEmptyAt     *time.Time
	LastDeliveredAt      *time.Time
	LastDeliveredQty     *int32
}

func (q *Queries) ApplyDeliveryToCustomer(ctx context.Context, arg ApplyDeliveryToCustomerParams) error {
	_, err := q.db.Exec(ctx, applyDeliveryToCustomer,
		arg.ID,
		arg.DepotID,
		arg.LoanBalance,
		arg.StampCount,
		arg.DaysPerGallon,
		arg.PredictionSamples,
		arg.PredictionConfidence,
		arg.PredictedEmptyAt,
		arg.LastDeliveredAt,
		arg.LastDeliveredQty,
	)
	return err
}

const insertLedger = `-- name: InsertLedger :one
INSERT INTO gallon_ledger (id, depot_id, customer_id, order_id, kind, delta, balance_after, note, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, depot_id, customer_id, order_id, kind, delta, balance_after, note, created_by, created_at
`

type InsertLedgerParams struct {
	ID           uuid.UUID
	DepotID      uuid.UUID
	CustomerID   uuid.UUID
	OrderID      *uuid.UUID
	Kind         string
	Delta        int32
	BalanceAfter int32
	Note         string
	CreatedBy    *uuid.UUID
}

func (q *Queries) InsertLedger(ctx context.Context, arg InsertLedgerParams) (GallonLedger, error) {
	row := q.db.QueryRow(ctx, insertLedger,
		arg.ID,
		arg.DepotID,
		arg.CustomerID,
		arg.OrderID,
		arg.Kind,
		arg.Delta,
		arg.BalanceAfter,
		arg.Note,
		arg.CreatedBy,
	)
	var i GallonLedger
	err := row.Scan(
		&i.ID,
		&i.DepotID,
		&i.CustomerID,
		&i.OrderID,
		&i.Kind,
		&i.Delta,
		&i.BalanceAfter,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listCourierQueue = `-- name: ListCourierQueue :many
SELECT orders.id, orders.depot_id, orders.customer_id, orders.code, orders.source, orders.status, orders.fulfilment, orders.scheduled_date, orders.delivery_name, orders.delivery_phone, orders.delivery_address, orders.delivery_note, orders.note, orders.refill_qty, orders.free_qty, orders.subtotal, orders.delivery_fee, orders.discount, orders.total, orders.payment_method, orders.payment_status, orders.paid_at, orders.courier_id, orders.gallons_returned, orders.reminder_id, orders.track_token_hash, orders.idempotency_key, orders.created_by, orders.created_at, orders.confirmed_at, orders.dispatched_at, orders.delivered_at, orders.cancelled_at, orders.cancel_reason, customers.lat, customers.lng, customers.area, customers.loan_balance
FROM orders
JOIN customers ON customers.id = orders.customer_id
WHERE orders.courier_id = $1 AND orders.depot_id = $2
  AND orders.status IN ('confirmed', 'on_delivery')
  AND orders.scheduled_date <= $3::date
ORDER BY orders.created_at
`

type ListCourierQueueParams struct {
	CourierID *uuid.UUID
	DepotID   uuid.UUID
	UntilDate time.Time
}

type ListCourierQueueRow struct {
	Order       Order
	Lat         *float64
	Lng         *float64
	Area        string
	LoanBalance int32
}

func (q *Queries) ListCourierQueue(ctx context.Context, arg ListCourierQueueParams) ([]ListCourierQueueRow, error) {
	rows, err := q.db.Query(ctx, listCourierQueue, arg.CourierID, arg.DepotID, arg.UntilDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCourierQueueRow{}
	for rows.Next() {
		var i ListCourierQueueRow
		if err := rows.Scan(
			&i.Order.ID,
			&i.Order.DepotID,
			&i.Order.CustomerID,
			&i.Order.Code,
			&i.Order.Source,
			&i.Order.Status,
			&i.Order.Fulfilment,
			&i.Order.ScheduledDate,
			&i.Order.DeliveryName,
			&i.Order.DeliveryPhone,
			&i.Order.DeliveryAddress,
			&i.Order.DeliveryNote,
			&i.Order.Note,
			&i.Order.RefillQty,
			&i.Order.FreeQty,
			&i.Order.Subtotal,
			&i.Order.DeliveryFee,
			&i.Order.Discount,
			&i.Order.Total,
			&i.Order.PaymentMethod,
			&i.Order.PaymentStatus,
			&i.Order.PaidAt,
			&i.Order.CourierID,
			&i.Order.GallonsReturned,
			&i.Order.ReminderID,
			&i.Order.TrackTokenHash,
			&i.Order.IdempotencyKey,
			&i.Order.CreatedBy,
			&i.Order.CreatedAt,
			&i.Order.ConfirmedAt,
			&i.Order.DispatchedAt,
			&i.Order.DeliveredAt,
			&i.Order.CancelledAt,
			&i.Order.CancelReason,
			&i.Lat,
			&i.Lng,
			&i.Area,
			&i.LoanBalance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerByCustomer = `-- name: ListLedgerByCustomer :many
SELECT id, depot_id, customer_id, order_id, kind, delta, balance_after, note, created_by, created_at FROM gallon_ledger
WHERE customer_id = $1 AND depot_id = $2
  AND ($4::timestamptz IS NULL OR (created_at, id) < ($4::timestamptz, $5::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListLedgerByCustomerParams struct {
	CustomerID uuid.UUID
	DepotID    uuid.UUID
	Limit      int32
	BeforeAt   *time.Time
	BeforeID   *uuid.UUID
}

func (q *Queries) ListLedgerByCustomer(ctx context.Context, arg ListLedgerByCustomerParams) ([]GallonLedger, error) {
	rows, err := q.db.Query(ctx, listLedgerByCustomer,
		arg.CustomerID,
		arg.DepotID,
		arg.Limit,
		arg.BeforeAt,
		arg.BeforeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GallonLedger{}
	for rows.Next() {
		var i GallonLedger
		if err := rows.Scan(
			&i.ID,
			&i.DepotID,
			&i.CustomerID,
			&i.OrderID,
			&i.Kind,
			&i.Delta,
			&i.BalanceAfter,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCustomerLoanBalance = `-- name: SetCustomerLoanBalance :exec
UPDATE customers SET loan_balance = $3, updated_at = now() WHERE id = $1 AND depot_id = $2
`

type SetCustomerLoanBalanceParams struct {
	ID          uuid.UUID
	DepotID     uuid.UUID
	LoanBalance int32
}

func (q *Queries) SetCustomerLoanBalance(ctx context.Context, arg SetCustomerLoanBalanceParams) error {
	_, err := q.db.Exec(ctx, setCustomerLoanBalance, arg.ID, arg.DepotID, arg.LoanBalance)
	return err
}

const sumLedgerByCustomer = `-- name: SumLedgerByCustomer :one
SELECT coalesce(sum(delta), 0)::bigint FROM gallon_ledger WHERE customer_id = $1
`

func (q *Queries) SumLedgerByCustomer(ctx context.Context, customerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumLedgerByCustomer, customerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
