// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type AuditLog struct {
	ID         uuid.UUID
	DepotID    uuid.UUID
	UserID     *uuid.UUID
	Action     string
	EntityType string
	EntityID   *uuid.UUID
	Meta       []byte
	Ip         *netip.Prefix
	CreatedAt  time.Time
}

type Customer struct {
	ID                   uuid.UUID
	DepotID              uuid.UUID
	Name                 string
	Phone                string
	Address              string
	AddressNote          string
	Area                 string
	Lat                  *float64
	Lng                  *float64
	TokenHash            []byte
	TokenEnc             []byte
	TokenRotatedAt       *time.Time
	Source               string
	IsVerified           bool
	UsualQty             int32
	LoanBalance          int32
	StampCount           int32
	DaysPerGallon        *float64
	PredictionSamples    int32
	PredictionConfidence string
	LastDeliveredAt      *time.Time
	LastDeliveredQty     *int32
	PredictedEmptyAt     *time.Time
	ReminderSnoozedUntil *time.Time
	IsActive             bool
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type Depot struct {
	ID                   uuid.UUID
	Name                 string
	Slug                 string
	Phone                string
	Address              string
	Lat                  *float64
	Lng                  *float64
	Timezone             string
	OpenTime             string
	CloseTime            string
	DeliveryFee          int64
	IsAcceptingOrders    bool
	AutoConfirmKnown     bool
	LoyaltyEvery         *int32
	ReminderLeadDays     int32
	DefaultDaysPerGallon float64
	IsDemo               bool
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type GallonLedger struct {
	ID           uuid.UUID
	DepotID      uuid.UUID
	CustomerID   uuid.UUID
	OrderID      *uuid.UUID
	Kind         string
	Delta        int32
	BalanceAfter int32
	Note         string
	CreatedBy    *uuid.UUID
	CreatedAt    time.Time
}

type Order struct {
	ID              uuid.UUID
	DepotID         uuid.UUID
	CustomerID      uuid.UUID
	Code            string
	Source          string
	Status          string
	Fulfilment      string
	ScheduledDate   time.Time
	DeliveryName    string
	DeliveryPhone   string
	DeliveryAddress string
	DeliveryNote    string
	Note            string
	RefillQty       int32
	FreeQty         int32
	Subtotal        int64
	DeliveryFee     int64
	Discount        int64
	Total           int64
	PaymentMethod   *string
	PaymentStatus   string
	PaidAt          *time.Time
	CourierID       *uuid.UUID
	GallonsReturned *int32
	ReminderID      *uuid.UUID
	TrackTokenHash  []byte
	IdempotencyKey  *string
	CreatedBy       *uuid.UUID
	CreatedAt       time.Time
	ConfirmedAt     *time.Time
	DispatchedAt    *time.Time
	DeliveredAt     *time.Time
	CancelledAt     *time.Time
	CancelReason    *string
}

type OrderCounter struct {
	DepotID uuid.UUID
	Day     time.Time
	LastNo  int32
}

type OrderEvent struct {
	ID             uuid.UUID
	DepotID        uuid.UUID
	OrderID        uuid.UUID
	Type           string
	ActorType      string
	ActorID        *uuid.UUID
	IdempotencyKey *string
	Meta           []byte
	CreatedAt      time.Time
}

type OrderItem struct {
	ID          uuid.UUID
	OrderID     uuid.UUID
	ProductID   uuid.UUID
	ProductName string
	ProductKind string
	UnitPrice   int64
	Qty         int32
	LineTotal   int64
}

type Product struct {
	ID        uuid.UUID
	DepotID   uuid.UUID
	Name      string
	Kind      string
	Price     int64
	IsActive  bool
	SortOrder int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Reminder struct {
	ID               uuid.UUID
	DepotID          uuid.UUID
	CustomerID       uuid.UUID
	DueDate          time.Time
	PredictedEmptyAt time.Time
	Status           string
	SentAt           *time.Time
	SentBy           *uuid.UUID
	OrderID          *uuid.UUID
	CreatedAt        time.Time
}

type Session struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	FamilyID  uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
	RotatedAt *time.Time
	RevokedAt *time.Time
	UserAgent string
	Ip        *netip.Prefix
	CreatedAt time.Time
}

type User struct {
	ID               uuid.UUID
	DepotID          uuid.UUID
	Role             string
	Name             string
	Phone            string
	PasswordHash     string
	IsActive         bool
	FailedLoginCount int32
	LockedUntil      *time.Time
	LastLoginAt      *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}
