// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order_items.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const insertOrderItem = `-- name: InsertOrderItem :exec
INSERT INTO order_items (id, order_id, product_id, product_name, product_kind, unit_price, qty, line_total)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertOrderItemParams struct {
	ID          uuid.UUID
	OrderID     uuid.UUID
	ProductID   uuid.UUID
	ProductName string
	ProductKind string
	UnitPrice   int64
	Qty         int32
	LineTotal   int64
}

func (q *Queries) InsertOrderItem(ctx context.Context, arg InsertOrderItemParams) error {
	_, err := q.db.Exec(ctx, insertOrderItem,
		arg.ID,
		arg.OrderID,
		arg.ProductID,
		arg.ProductName,
		arg.ProductKind,
		arg.UnitPrice,
		arg.Qty,
		arg.LineTotal,
	)
	return err
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT id, order_id, product_id, product_name, product_kind, unit_price, qty, line_total FROM order_items WHERE order_id = ANY($1::uuid[]) ORDER BY order_id, product_name
`

func (q *Queries) ListOrderItems(ctx context.Context, dollar_1 []uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItems, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.ProductName,
			&i.ProductKind,
			&i.UnitPrice,
			&i.Qty,
			&i.LineTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
