// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order_events.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const insertOrderEvent = `-- name: InsertOrderEvent :exec
INSERT INTO order_events (id, depot_id, order_id, type, actor_type, actor_id, idempotency_key, meta)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertOrderEventParams struct {
	ID             uuid.UUID
	DepotID        uuid.UUID
	OrderID        uuid.UUID
	Type           string
	ActorType      string
	ActorID        *uuid.UUID
	IdempotencyKey *string
	Meta           []byte
}

func (q *Queries) InsertOrderEvent(ctx context.Context, arg InsertOrderEventParams) error {
	_, err := q.db.Exec(ctx, insertOrderEvent,
		arg.ID,
		arg.DepotID,
		arg.OrderID,
		arg.Type,
		arg.ActorType,
		arg.ActorID,
		arg.IdempotencyKey,
		arg.Meta,
	)
	return err
}

const listOrderEvents = `-- name: ListOrderEvents :many
SELECT id, depot_id, order_id, type, actor_type, actor_id, idempotency_key, meta, created_at FROM order_events WHERE order_id = $1 AND depot_id = $2 ORDER BY created_at, id
`

type ListOrderEventsParams struct {
	OrderID uuid.UUID
	DepotID uuid.UUID
}

func (q *Queries) ListOrderEvents(ctx context.Context, arg ListOrderEventsParams) ([]OrderEvent, error) {
	rows, err := q.db.Query(ctx, listOrderEvents, arg.OrderID, arg.DepotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderEvent{}
	for rows.Next() {
		var i OrderEvent
		if err := rows.Scan(
			&i.ID,
			&i.DepotID,
			&i.OrderID,
			&i.Type,
			&i.ActorType,
			&i.ActorID,
			&i.IdempotencyKey,
			&i.Meta,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orderEventExists = `-- name: OrderEventExists :one
SELECT EXISTS (SELECT 1 FROM order_events WHERE order_id = $1 AND idempotency_key = $2)
`

type OrderEventExistsParams struct {
	OrderID        uuid.UUID
	IdempotencyKey *string
}

func (q *Queries) OrderEventExists(ctx context.Context, arg OrderEventExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, orderEventExists, arg.OrderID, arg.IdempotencyKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
