// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const assignCourier = `-- name: AssignCourier :one
UPDATE orders SET courier_id = $3
WHERE id = $1 AND depot_id = $2 AND status IN ('confirmed', 'on_delivery')
RETURNING id, depot_id, customer_id, code, source, status, fulfilment, scheduled_date, delivery_name, delivery_phone, delivery_address, delivery_note, note, refill_qty, free_qty, subtotal, delivery_fee, discount, total, payment_method, payment_status, paid_at, courier_id, gallons_returned, reminder_id, track_token_hash, idempotency_key, created_by, created_at, confirmed_at, dispatched_at, delivered_at, cancelled_at, cancel_reason
`

type AssignCourierParams struct {
	ID        uuid.UUID
	DepotID   uuid.UUID
	CourierID *uuid.UUID
}

func (q *Queries) AssignCourier(ctx context.Context, arg AssignCourierParams) (Order, error) {
	row := q.db.QueryRow(ctx, assignCourier, arg.ID, arg.DepotID, arg.CourierID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.DepotID,
		&i.CustomerID,
		&i.Code,
		&i.Source,
		&i.Status,
		&i.Fulfilment,
		&i.ScheduledDate,
		&i.DeliveryName,
		&i.DeliveryPhone,
		&i.DeliveryAddress,
		&i.DeliveryNote,
		&i.Note,
		&i.RefillQty,
		&i.FreeQty,
		&i.Subtotal,
		&i.DeliveryFee,
		&i.Discount,
		&i.Total,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.CourierID,
		&i.GallonsReturned,
		&i.ReminderID,
		&i.TrackTokenHash,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.DispatchedAt,
		&i.DeliveredAt,
		&i.CancelledAt,
		&i.CancelReason,
	)
	return i, err
}

const cancelOrder = `-- name: CancelOrder :one
UPDATE orders SET status = 'cancelled', cancelled_at = $3, cancel_reason = $4
WHERE id = $1 AND depot_id = $2 AND status IN ('pending', 'confirmed', 'on_delivery')
RETURNING id, depot_id, customer_id, code, source, status, fulfilment, scheduled_date, delivery_name, delivery_phone, delivery_address, delivery_note, note, refill_qty, free_qty, subtotal, delivery_fee, discount, total, payment_method, payment_status, paid_at, courier_id, gallons_returned, reminder_id, track_token_hash, idempotency_key, created_by, created_at, confirmed_at, dispatched_at, delivered_at, cancelled_at, cancel_reason
`

type CancelOrderParams struct {
	ID           uuid.UUID
	DepotID      uuid.UUID
	CancelledAt  *time.Time
	CancelReason *string
}

func (q *Queries) CancelOrder(ctx context.Context, arg CancelOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, cancelOrder,
		arg.ID,
		arg.DepotID,
		arg.CancelledAt,
		arg.CancelReason,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.DepotID,
		&i.CustomerID,
		&i.Code,
		&i.Source,
		&i.Status,
		&i.Fulfilment,
		&i.ScheduledDate,
		&i.DeliveryName,
		&i.DeliveryPhone,
		&i.DeliveryAddress,
		&i.DeliveryNote,
		&i.Note,
		&i.RefillQty,
		&i.FreeQty,
		&i.Subtotal,
		&i.DeliveryFee,
		&i.Discount,
		&i.Total,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.CourierID,
		&i.GallonsReturned,
		&i.ReminderID,
		&i.TrackTokenHash,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.DispatchedAt,
		&i.DeliveredAt,
		&i.CancelledAt,
		&i.CancelReason,
	)
	return i, err
}

const cancelPendingOrderByCustomer = `-- name: CancelPendingOrderByCustomer :one
UPDATE orders SET status = 'cancelled', cancelled_at = $2, cancel_reason = 'Dibatalkan pelanggan'
WHERE id = $1 AND status = 'pending'
RETURNING id, depot_id, customer_id, code, source, status, fulfilment, scheduled_date, delivery_name, delivery_phone, delivery_address, delivery_note, note, refill_qty, free_qty, subtotal, delivery_fee, discount, total, payment_method, payment_status, paid_at, courier_id, gallons_returned, reminder_id, track_token_hash, idempotency_key, created_by, created_at, confirmed_at, dispatched_at, delivered_at, cancelled_at, cancel_reason
`

type CancelPendingOrderByCustomerParams struct {
	ID          uuid.UUID
	CancelledAt *time.Time
}

func (q *Queries) CancelPendingOrderByCustomer(ctx context.Context, arg CancelPendingOrderByCustomerParams) (Order, error) {
	row := q.db.QueryRow(ctx, cancelPendingOrderByCustomer, arg.ID, arg.CancelledAt)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.DepotID,
		&i.CustomerID,
		&i.Code,
		&i.Source,
		&i.Status,
		&i.Fulfilment,
		&i.ScheduledDate,
		&i.DeliveryName,
		&i.DeliveryPhone,
		&i.DeliveryAddress,
		&i.DeliveryNote,
		&i.Note,
		&i.RefillQty,
		&i.FreeQty,
		&i.Subtotal,
		&i.DeliveryFee,
		&i.Discount,
		&i.Total,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.CourierID,
		&i.GallonsReturned,
		&i.ReminderID,
		&i.TrackTokenHash,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.DispatchedAt,
		&i.DeliveredAt,
		&i.CancelledAt,
		&i.CancelReason,
	)
	return i, err
}

const confirmOrder = `-- name: ConfirmOrder :one
UPDATE orders SET status = 'confirmed', confirmed_at = $3
WHERE id = $1 AND depot_id = $2 AND status = 'pending'
RETURNING id, depot_id, customer_id, code, source, status, fulfilment, scheduled_date, delivery_name, delivery_phone, delivery_address, delivery_note, note, refill_qty, free_qty, subtotal, delivery_fee, discount, total, payment_method, payment_status, paid_at, courier_id, gallons_returned, reminder_id, track_token_hash, idempotency_key, created_by, created_at, confirmed_at, dispatched_at, delivered_at, cancelled_at, cancel_reason
`

type ConfirmOrderParams struct {
	ID          uuid.UUID
	DepotID     uuid.UUID
	ConfirmedAt *time.Time
}

func (q *Queries) ConfirmOrder(ctx context.Context, arg ConfirmOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, confirmOrder, arg.ID, arg.DepotID, arg.ConfirmedAt)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.DepotID,
		&i.CustomerID,
		&i.Code,
		&i.Source,
		&i.Status,
		&i.Fulfilment,
		&i.ScheduledDate,
		&i.DeliveryName,
		&i.DeliveryPhone,
		&i.DeliveryAddress,
		&i.DeliveryNote,
		&i.Note,
		&i.RefillQty,
		&i.FreeQty,
		&i.Subtotal,
		&i.DeliveryFee,
		&i.Discount,
		&i.Total,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.CourierID,
		&i.GallonsReturned,
		&i.ReminderID,
		&i.TrackTokenHash,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.DispatchedAt,
		&i.DeliveredAt,
		&i.CancelledAt,
		&i.CancelReason,
	)
	return i, err
}

const countActiveOrdersByCustomer = `-- name: CountActiveOrdersByCustomer :one
SELECT count(*) FROM orders WHERE customer_id = $1 AND status IN ('pending', 'confirmed', 'on_delivery')
`

func (q *Queries) CountActiveOrdersByCustomer(ctx context.Context, customerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveOrdersByCustomer, customerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingOrdersByPhone = `-- name: CountPendingOrdersByPhone :one
SELECT count(*) FROM orders WHERE depot_id = $1 AND delivery_phone = $2 AND status = 'pending'
`

type CountPendingOrdersByPhoneParams struct {
	DepotID       uuid.UUID
	DeliveryPhone string
}

func (q *Queries) CountPendingOrdersByPhone(ctx context.Context, arg CountPendingOrdersByPhoneParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingOrdersByPhone, arg.DepotID, arg.DeliveryPhone)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
  id, depot_id, customer_id, code, source, status, fulfilment, scheduled_date,
  delivery_name, delivery_phone, delivery_address, delivery_note, note,
  refill_qty, free_qty, subtotal, delivery_fee, discount, total,
  courier_id, reminder_id, track_token_hash, idempotency_key, created_by, created_at, confirmed_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8,
  $9, $10, $11, $12, $13,
  $14, $15, $16, $17, $18, $19,
  $20, $21, $22, $23, $24, $25, $26
)
RETURNING id, depot_id, customer_id, code, source, status, fulfilment, scheduled_date, delivery_name, delivery_phone, delivery_address, delivery_note, note, refill_qty, free_qty, subtotal, delivery_fee, discount, total, payment_method, payment_status, paid_at, courier_id, gallons_returned, reminder_id, track_token_hash, idempotency_key, created_by, created_at, confirmed_at, dispatched_at, delivered_at, cancelled_at, cancel_reason
`

type CreateOrderParams struct {
	ID              uuid.UUID
	DepotID         uuid.UUID
	CustomerID      uuid.UUID
	Code            string
	Source          string
	Status          string
	Fulfilment      string
	ScheduledDate   time.Time
	DeliveryName    string
	DeliveryPhone   string
	DeliveryAddress string
	DeliveryNote    string
	Note            string
	RefillQty       int32
	FreeQty         int32
	Subtotal        int64
	DeliveryFee     int64
	Discount        int64
	Total           int64
	CourierID       *uuid.UUID
	ReminderID      *uuid.UUID
	TrackTokenHash  []byte
	IdempotencyKey  *string
	CreatedBy       *uuid.UUID
	CreatedAt       time.Time
	ConfirmedAt     *time.Time
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.DepotID,
		arg.CustomerID,
		arg.Code,
		arg.Source,
		arg.Status,
		arg.Fulfilment,
		arg.ScheduledDate,
		arg.DeliveryName,
		arg.DeliveryPhone,
		arg.DeliveryAddress,
		arg.DeliveryNote,
		arg.Note,
		arg.RefillQty,
		arg.FreeQty,
		arg.Subtotal,
		arg.DeliveryFee,
		arg.Discount,
		arg.Total,
		arg.CourierID,
		arg.ReminderID,
		arg.TrackTokenHash,
		arg.IdempotencyKey,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ConfirmedAt,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.DepotID,
		&i.CustomerID,
		&i.Code,
		&i.Source,
		&i.Status,
		&i.Fulfilment,
		&i.ScheduledDate,
		&i.DeliveryName,
		&i.DeliveryPhone,
		&i.DeliveryAddress,
		&i.DeliveryNote,
		&i.Note,
		&i.RefillQty,
		&i.FreeQty,
		&i.Subtotal,
		&i.DeliveryFee,
		&i.Discount,
		&i.Total,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.CourierID,
		&i.GallonsReturned,
		&i.ReminderID,
		&i.TrackTokenHash,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.DispatchedAt,
		&i.DeliveredAt,
		&i.CancelledAt,
		&i.CancelReason,
	)
	return i, err
}

const deliverOrder = `-- name: DeliverOrder :one
UPDATE orders
SET status = 'delivered', delivered_at = $3, gallons_returned = $4,
    payment_method = $5, payment_status = $6, paid_at = CASE WHEN $6 = 'paid' THEN $3 ELSE paid_at END
WHERE id = $1 AND depot_id = $2 AND status = $7::text
RETURNING id, depot_id, customer_id, code, source, status, fulfilment, scheduled_date, delivery_name, delivery_phone, delivery_address, delivery_note, note, refill_qty, free_qty, subtotal, delivery_fee, discount, total, payment_method, payment_status, paid_at, courier_id, gallons_returned, reminder_id, track_token_hash, idempotency_key, created_by, created_at, confirmed_at, dispatched_at, delivered_at, cancelled_at, cancel_reason
`

type DeliverOrderParams struct {
	ID              uuid.UUID
	DepotID         uuid.UUID
	DeliveredAt     *time.Time
	GallonsReturned *int32
	PaymentMethod   *string
	PaymentStatus   string
	FromStatus      string
}

func (q *Queries) DeliverOrder(ctx context.Context, arg DeliverOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, deliverOrder,
		arg.ID,
		arg.DepotID,
		arg.DeliveredAt,
		arg.GallonsReturned,
		arg.PaymentMethod,
		arg.PaymentStatus,
		arg.FromStatus,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.DepotID,
		&i.CustomerID,
		&i.Code,
		&i.Source,
		&i.Status,
		&i.Fulfilment,
		&i.ScheduledDate,
		&i.DeliveryName,
		&i.DeliveryPhone,
		&i.DeliveryAddress,
		&i.DeliveryNote,
		&i.Note,
		&i.RefillQty,
		&i.FreeQty,
		&i.Subtotal,
		&i.DeliveryFee,
		&i.Discount,
		&i.Total,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.CourierID,
		&i.GallonsReturned,
		&i.ReminderID,
		&i.TrackTokenHash,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.DispatchedAt,
		&i.DeliveredAt,
		&i.CancelledAt,
		&i.CancelReason,
	)
	return i, err
}

const dispatchOrder = `-- name: DispatchOrder :one
UPDATE orders SET status = 'on_delivery', dispatched_at = $3, courier_id = COALESCE(courier_id, $4::uuid)
WHERE id = $1 AND depot_id = $2 AND status = 'confirmed'
RETURNING id, depot_id, customer_id, code, source, status, fulfilment, scheduled_date, delivery_name, delivery_phone, delivery_address, delivery_note, note, refill_qty, free_qty, subtotal, delivery_fee, discount, total, payment_method, payment_status, paid_at, courier_id, gallons_returned, reminder_id, track_token_hash, idempotency_key, created_by, created_at, confirmed_at, dispatched_at, delivered_at, cancelled_at, cancel_reason
`

type DispatchOrderParams struct {
	ID           uuid.UUID
	DepotID      uuid.UUID
	DispatchedAt *time.Time
	CourierID    *uuid.UUID
}

func (q *Queries) DispatchOrder(ctx context.Context, arg DispatchOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, dispatchOrder,
		arg.ID,
		arg.DepotID,
		arg.DispatchedAt,
		arg.CourierID,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.DepotID,
		&i.CustomerID,
		&i.Code,
		&i.Source,
		&i.Status,
		&i.Fulfilment,
		&i.ScheduledDate,
		&i.DeliveryName,
		&i.DeliveryPhone,
		&i.DeliveryAddress,
		&i.DeliveryNote,
		&i.Note,
		&i.RefillQty,
		&i.FreeQty,
		&i.Subtotal,
		&i.DeliveryFee,
		&i.Discount,
		&i.Total,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.CourierID,
		&i.GallonsReturned,
		&i.ReminderID,
		&i.TrackTokenHash,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.DispatchedAt,
		&i.DeliveredAt,
		&i.CancelledAt,
		&i.CancelReason,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, depot_id, customer_id, code, source, status, fulfilment, scheduled_date, delivery_name, delivery_phone, delivery_address, delivery_note, note, refill_qty, free_qty, subtotal, delivery_fee, discount, total, payment_method, payment_status, paid_at, courier_id, gallons_returned, reminder_id, track_token_hash, idempotency_key, created_by, created_at, confirmed_at, dispatched_at, delivered_at, cancelled_at, cancel_reason FROM orders WHERE id = $1 AND depot_id = $2
`

type GetOrderParams struct {
	ID      uuid.UUID
	DepotID uuid.UUID
}

func (q *Queries) GetOrder(ctx context.Context, arg GetOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, arg.ID, arg.DepotID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.DepotID,
		&i.CustomerID,
		&i.Code,
		&i.Source,
		&i.Status,
		&i.Fulfilment,
		&i.ScheduledDate,
		&i.DeliveryName,
		&i.DeliveryPhone,
		&i.DeliveryAddress,
		&i.DeliveryNote,
		&i.Note,
		&i.RefillQty,
		&i.FreeQty,
		&i.Subtotal,
		&i.DeliveryFee,
		&i.Discount,
		&i.Total,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.CourierID,
		&i.GallonsReturned,
		&i.ReminderID,
		&i.TrackTokenHash,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.DispatchedAt,
		&i.DeliveredAt,
		&i.CancelledAt,
		&i.CancelReason,
	)
	return i, err
}

const getOrderByIdempotencyKey = `-- name: GetOrderByIdempotencyKey :one
SELECT id, depot_id, customer_id, code, source, status, fulfilment, scheduled_date, delivery_name, delivery_phone, delivery_address, delivery_note, note, refill_qty, free_qty, subtotal, delivery_fee, discount, total, payment_method, payment_status, paid_at, courier_id, gallons_returned, reminder_id, track_token_hash, idempotency_key, created_by, created_at, confirmed_at, dispatched_at, delivered_at, cancelled_at, cancel_reason FROM orders WHERE depot_id = $1 AND idempotency_key = $2
`

type GetOrderByIdempotencyKeyParams struct {
	DepotID        uuid.UUID
	IdempotencyKey *string
}

func (q *Queries) GetOrderByIdempotencyKey(ctx context.Context, arg GetOrderByIdempotencyKeyParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByIdempotencyKey, arg.DepotID, arg.IdempotencyKey)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.DepotID,
		&i.CustomerID,
		&i.Code,
		&i.Source,
		&i.Status,
		&i.Fulfilment,
		&i.ScheduledDate,
		&i.DeliveryName,
		&i.DeliveryPhone,
		&i.DeliveryAddress,
		&i.DeliveryNote,
		&i.Note,
		&i.RefillQty,
		&i.FreeQty,
		&i.Subtotal,
		&i.DeliveryFee,
		&i.Discount,
		&i.Total,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.CourierID,
		&i.GallonsReturned,
		&i.ReminderID,
		&i.TrackTokenHash,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.DispatchedAt,
		&i.DeliveredAt,
		&i.CancelledAt,
		&i.CancelReason,
	)
	return i, err
}

const getOrderByTrackTokenHash = `-- name: GetOrderByTrackTokenHash :one
SELECT id, depot_id, customer_id, code, source, status, fulfilment, scheduled_date, delivery_name, delivery_phone, delivery_address, delivery_note, note, refill_qty, free_qty, subtotal, delivery_fee, discount, total, payment_method, payment_status, paid_at, courier_id, gallons_returned, reminder_id, track_token_hash, idempotency_key, created_by, created_at, confirmed_at, dispatched_at, delivered_at, cancelled_at, cancel_reason FROM orders WHERE track_token_hash = $1
`

func (q *Queries) GetOrderByTrackTokenHash(ctx context.Context, trackTokenHash []byte) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByTrackTokenHash, trackTokenHash)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.DepotID,
		&i.CustomerID,
		&i.Code,
		&i.Source,
		&i.Status,
		&i.Fulfilment,
		&i.ScheduledDate,
		&i.DeliveryName,
		&i.DeliveryPhone,
		&i.DeliveryAddress,
		&i.DeliveryNote,
		&i.Note,
		&i.RefillQty,
		&i.FreeQty,
		&i.Subtotal,
		&i.DeliveryFee,
		&i.Discount,
		&i.Total,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.CourierID,
		&i.GallonsReturned,
		&i.ReminderID,
		&i.TrackTokenHash,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.DispatchedAt,
		&i.DeliveredAt,
		&i.CancelledAt,
		&i.CancelReason,
	)
	return i, err
}

const getOrderForUpdate = `-- name: GetOrderForUpdate :one
SELECT id, depot_id, customer_id, code, source, status, fulfilment, scheduled_date, delivery_name, delivery_phone, delivery_address, delivery_note, note, refill_qty, free_qty, subtotal, delivery_fee, discount, total, payment_method, payment_status, paid_at, courier_id, gallons_returned, reminder_id, track_token_hash, idempotency_key, created_by, created_at, confirmed_at, dispatched_at, delivered_at, cancelled_at, cancel_reason FROM orders WHERE id = $1 AND depot_id = $2 FOR UPDATE
`

type GetOrderForUpdateParams struct {
	ID      uuid.UUID
	DepotID uuid.UUID
}

func (q *Queries) GetOrderForUpdate(ctx context.Context, arg GetOrderForUpdateParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderForUpdate, arg.ID, arg.DepotID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.DepotID,
		&i.CustomerID,
		&i.Code,
		&i.Source,
		&i.Status,
		&i.Fulfilment,
		&i.ScheduledDate,
		&i.DeliveryName,
		&i.DeliveryPhone,
		&i.DeliveryAddress,
		&i.DeliveryNote,
		&i.Note,
		&i.RefillQty,
		&i.FreeQty,
		&i.Subtotal,
		&i.DeliveryFee,
		&i.Discount,
		&i.Total,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.CourierID,
		&i.GallonsReturned,
		&i.ReminderID,
		&i.TrackTokenHash,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.DispatchedAt,
		&i.DeliveredAt,
		&i.CancelledAt,
		&i.CancelReason,
	)
	return i, err
}

const hasActiveFreeOrder = `-- name: HasActiveFreeOrder :one
SELECT EXISTS (
  SELECT 1 FROM orders WHERE customer_id = $1 AND free_qty > 0 AND status IN ('pending', 'confirmed', 'on_delivery')
)
`

func (q *Queries) HasActiveFreeOrder(ctx context.Context, customerID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveFreeOrder, customerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listActiveOrders = `-- name: ListActiveOrders :many
SELECT id, depot_id, customer_id, code, source, status, fulfilment, scheduled_date, delivery_name, delivery_phone, delivery_address, delivery_note, note, refill_qty, free_qty, subtotal, delivery_fee, discount, total, payment_method, payment_status, paid_at, courier_id, gallons_returned, reminder_id, track_token_hash, idempotency_key, created_by, created_at, confirmed_at, dispatched_at, delivered_at, cancelled_at, cancel_reason FROM orders
WHERE depot_id = $1 AND status IN ('pending', 'confirmed', 'on_delivery')
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListActiveOrdersParams struct {
	DepotID uuid.UUID
	Limit   int32
}

func (q *Queries) ListActiveOrders(ctx context.Context, arg ListActiveOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listActiveOrders, arg.DepotID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.DepotID,
			&i.CustomerID,
			&i.Code,
			&i.Source,
			&i.Status,
			&i.Fulfilment,
			&i.ScheduledDate,
			&i.DeliveryName,
			&i.DeliveryPhone,
			&i.DeliveryAddress,
			&i.DeliveryNote,
			&i.Note,
			&i.RefillQty,
			&i.FreeQty,
			&i.Subtotal,
			&i.DeliveryFee,
			&i.Discount,
			&i.Total,
			&i.PaymentMethod,
			&i.PaymentStatus,
			&i.PaidAt,
			&i.CourierID,
			&i.GallonsReturned,
			&i.ReminderID,
			&i.TrackTokenHash,
			&i.IdempotencyKey,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ConfirmedAt,
			&i.DispatchedAt,
			&i.DeliveredAt,
			&i.CancelledAt,
			&i.CancelReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveOrdersByCustomer = `-- name: ListActiveOrdersByCustomer :many
SELECT id, depot_id, customer_id, code, source, status, fulfilment, scheduled_date, delivery_name, delivery_phone, delivery_address, delivery_note, note, refill_qty, free_qty, subtotal, delivery_fee, discount, total, payment_method, payment_status, paid_at, courier_id, gallons_returned, reminder_id, track_token_hash, idempotency_key, created_by, created_at, confirmed_at, dispatched_at, delivered_at, cancelled_at, cancel_reason FROM orders
WHERE customer_id = $1 AND status IN ('pending', 'confirmed', 'on_delivery')
ORDER BY created_at DESC
`

func (q *Queries) ListActiveOrdersByCustomer(ctx context.Context, customerID uuid.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, listActiveOrdersByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.DepotID,
			&i.CustomerID,
			&i.Code,
			&i.Source,
			&i.Status,
			&i.Fulfilment,
			&i.ScheduledDate,
			&i.DeliveryName,
			&i.DeliveryPhone,
			&i.DeliveryAddress,
			&i.DeliveryNote,
			&i.Note,
			&i.RefillQty,
			&i.FreeQty,
			&i.Subtotal,
			&i.DeliveryFee,
			&i.Discount,
			&i.Total,
			&i.PaymentMethod,
			&i.PaymentStatus,
			&i.PaidAt,
			&i.CourierID,
			&i.GallonsReturned,
			&i.ReminderID,
			&i.TrackTokenHash,
			&i.IdempotencyKey,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ConfirmedAt,
			&i.DispatchedAt,
			&i.DeliveredAt,
			&i.CancelledAt,
			&i.CancelReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT id, depot_id, customer_id, code, source, status, fulfilment, scheduled_date, delivery_name, delivery_phone, delivery_address, delivery_note, note, refill_qty, free_qty, subtotal, delivery_fee, discount, total, payment_method, payment_status, paid_at, courier_id, gallons_returned, reminder_id, track_token_hash, idempotency_key, created_by, created_at, confirmed_at, dispatched_at, delivered_at, cancelled_at, cancel_reason FROM orders
WHERE depot_id = $1
  AND ($3::text IS NULL OR status = $3::text)
  AND ($4::date IS NULL OR scheduled_date = $4::date)
  AND ($5::uuid IS NULL OR courier_id = $5::uuid)
  AND ($6::timestamptz IS NULL OR (created_at, id) < ($6::timestamptz, $7::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListOrdersParams struct {
	DepotID       uuid.UUID
	Limit         int32
	Status        *string
	ScheduledDate *time.Time
	CourierID     *uuid.UUID
	BeforeAt      *time.Time
	BeforeID      *uuid.UUID
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders,
		arg.DepotID,
		arg.Limit,
		arg.Status,
		arg.ScheduledDate,
		arg.CourierID,
		arg.BeforeAt,
		arg.BeforeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.DepotID,
			&i.CustomerID,
			&i.Code,
			&i.Source,
			&i.Status,
			&i.Fulfilment,
			&i.ScheduledDate,
			&i.DeliveryName,
			&i.DeliveryPhone,
			&i.DeliveryAddress,
			&i.DeliveryNote,
			&i.Note,
			&i.RefillQty,
			&i.FreeQty,
			&i.Subtotal,
			&i.DeliveryFee,
			&i.Discount,
			&i.Total,
			&i.PaymentMethod,
			&i.PaymentStatus,
			&i.PaidAt,
			&i.CourierID,
			&i.GallonsReturned,
			&i.ReminderID,
			&i.TrackTokenHash,
			&i.IdempotencyKey,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ConfirmedAt,
			&i.DispatchedAt,
			&i.DeliveredAt,
			&i.CancelledAt,
			&i.CancelReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByCustomer = `-- name: ListOrdersByCustomer :many
SELECT id, depot_id, customer_id, code, source, status, fulfilment, scheduled_date, delivery_name, delivery_phone, delivery_address, delivery_note, note, refill_qty, free_qty, subtotal, delivery_fee, discount, total, payment_method, payment_status, paid_at, courier_id, gallons_returned, reminder_id, track_token_hash, idempotency_key, created_by, created_at, confirmed_at, dispatched_at, delivered_at, cancelled_at, cancel_reason FROM orders
WHERE customer_id = $1 AND depot_id = $2
  AND ($4::timestamptz IS NULL OR (created_at, id) < ($4::timestamptz, $5::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListOrdersByCustomerParams struct {
	CustomerID uuid.UUID
	DepotID    uuid.UUID
	Limit      int32
	BeforeAt   *time.Time
	BeforeID   *uuid.UUID
}

func (q *Queries) ListOrdersByCustomer(ctx context.Context, arg ListOrdersByCustomerParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByCustomer,
		arg.CustomerID,
		arg.DepotID,
		arg.Limit,
		arg.BeforeAt,
		arg.BeforeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.DepotID,
			&i.CustomerID,
			&i.Code,
			&i.Source,
			&i.Status,
			&i.Fulfilment,
			&i.ScheduledDate,
			&i.DeliveryName,
			&i.DeliveryPhone,
			&i.DeliveryAddress,
			&i.DeliveryNote,
			&i.Note,
			&i.RefillQty,
			&i.FreeQty,
			&i.Subtotal,
			&i.DeliveryFee,
			&i.Discount,
			&i.Total,
			&i.PaymentMethod,
			&i.PaymentStatus,
			&i.PaidAt,
			&i.CourierID,
			&i.GallonsReturned,
			&i.ReminderID,
			&i.TrackTokenHash,
			&i.IdempotencyKey,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ConfirmedAt,
			&i.DispatchedAt,
			&i.DeliveredAt,
			&i.CancelledAt,
			&i.CancelReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentDeliveries = `-- name: ListRecentDeliveries :many
SELECT delivered_at, refill_qty FROM orders
WHERE customer_id = $1 AND status = 'delivered' AND refill_qty > 0 AND delivered_at IS NOT NULL
ORDER BY delivered_at DESC
LIMIT $2
`

type ListRecentDeliveriesParams struct {
	CustomerID uuid.UUID
	Limit      int32
}

type ListRecentDeliveriesRow struct {
	DeliveredAt *time.Time
	RefillQty   int32
}

func (q *Queries) ListRecentDeliveries(ctx context.Context, arg ListRecentDeliveriesParams) ([]ListRecentDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, listRecentDeliveries, arg.CustomerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentDeliveriesRow{}
	for rows.Next() {
		var i ListRecentDeliveriesRow
		if err := rows.Scan(&i.DeliveredAt, &i.RefillQty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrderPaid = `-- name: MarkOrderPaid :one
UPDATE orders SET payment_status = 'paid', paid_at = $3, payment_method = COALESCE($4, payment_method, 'cash')
WHERE id = $1 AND depot_id = $2 AND payment_status = 'unpaid'
RETURNING id, depot_id, customer_id, code, source, status, fulfilment, scheduled_date, delivery_name, delivery_phone, delivery_address, delivery_note, note, refill_qty, free_qty, subtotal, delivery_fee, discount, total, payment_method, payment_status, paid_at, courier_id, gallons_returned, reminder_id, track_token_hash, idempotency_key, created_by, created_at, confirmed_at, dispatched_at, delivered_at, cancelled_at, cancel_reason
`

type MarkOrderPaidParams struct {
	ID            uuid.UUID
	DepotID       uuid.UUID
	PaidAt        *time.Time
	PaymentMethod *string
}

func (q *Queries) MarkOrderPaid(ctx context.Context, arg MarkOrderPaidParams) (Order, error) {
	row := q.db.QueryRow(ctx, markOrderPaid,
		arg.ID,
		arg.DepotID,
		arg.PaidAt,
		arg.PaymentMethod,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.DepotID,
		&i.CustomerID,
		&i.Code,
		&i.Source,
		&i.Status,
		&i.Fulfilment,
		&i.ScheduledDate,
		&i.DeliveryName,
		&i.DeliveryPhone,
		&i.DeliveryAddress,
		&i.DeliveryNote,
		&i.Note,
		&i.RefillQty,
		&i.FreeQty,
		&i.Subtotal,
		&i.DeliveryFee,
		&i.Discount,
		&i.Total,
		&i.PaymentMethod,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.CourierID,
		&i.GallonsReturned,
		&i.ReminderID,
		&i.TrackTokenHash,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.DispatchedAt,
		&i.DeliveredAt,
		&i.CancelledAt,
		&i.CancelReason,
	)
	return i, err
}

const nextOrderNumber = `-- name: NextOrderNumber :one
INSERT INTO order_counters (depot_id, day, last_no) VALUES ($1, $2, 1)
ON CONFLICT (depot_id, day) DO UPDATE SET last_no = order_counters.last_no + 1
RETURNING last_no
`

type NextOrderNumberParams struct {
	DepotID uuid.UUID
	Day     time.Time
}

func (q *Queries) NextOrderNumber(ctx context.Context, arg NextOrderNumberParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextOrderNumber, arg.DepotID, arg.Day)
	var last_no int32
	err := row.Scan(&last_no)
	return last_no, err
}
