// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (id, depot_id, name, kind, price, sort_order)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, depot_id, name, kind, price, is_active, sort_order, created_at, updated_at
`

type CreateProductParams struct {
	ID        uuid.UUID
	DepotID   uuid.UUID
	Name      string
	Kind      string
	Price     int64
	SortOrder int32
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ID,
		arg.DepotID,
		arg.Name,
		arg.Kind,
		arg.Price,
		arg.SortOrder,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.DepotID,
		&i.Name,
		&i.Kind,
		&i.Price,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, depot_id, name, kind, price, is_active, sort_order, created_at, updated_at FROM products WHERE id = $1 AND depot_id = $2
`

type GetProductParams struct {
	ID      uuid.UUID
	DepotID uuid.UUID
}

func (q *Queries) GetProduct(ctx context.Context, arg GetProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, arg.ID, arg.DepotID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.DepotID,
		&i.Name,
		&i.Kind,
		&i.Price,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRefillProduct = `-- name: GetRefillProduct :one
SELECT id, depot_id, name, kind, price, is_active, sort_order, created_at, updated_at FROM products WHERE depot_id = $1 AND kind = 'refill' AND is_active ORDER BY sort_order, created_at LIMIT 1
`

func (q *Queries) GetRefillProduct(ctx context.Context, depotID uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getRefillProduct, depotID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.DepotID,
		&i.Name,
		&i.Kind,
		&i.Price,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveProducts = `-- name: ListActiveProducts :many
SELECT id, depot_id, name, kind, price, is_active, sort_order, created_at, updated_at FROM products WHERE depot_id = $1 AND is_active ORDER BY sort_order, created_at
`

func (q *Queries) ListActiveProducts(ctx context.Context, depotID uuid.UUID) ([]Product, error) {
	rows, err := q.db.Query(ctx, listActiveProducts, depotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.DepotID,
			&i.Name,
			&i.Kind,
			&i.Price,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, depot_id, name, kind, price, is_active, sort_order, created_at, updated_at FROM products WHERE depot_id = $1 ORDER BY sort_order, created_at
`

func (q *Queries) ListProducts(ctx context.Context, depotID uuid.UUID) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, depotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.DepotID,
			&i.Name,
			&i.Kind,
			&i.Price,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = COALESCE($3, name),
    price = COALESCE($4, price),
    kind = COALESCE($5, kind),
    is_active = COALESCE($6, is_active),
    sort_order = COALESCE($7, sort_order),
    updated_at = now()
WHERE id = $1 AND depot_id = $2
RETURNING id, depot_id, name, kind, price, is_active, sort_order, created_at, updated_at
`

type UpdateProductParams struct {
	ID        uuid.UUID
	DepotID   uuid.UUID
	Name      *string
	Price     *int64
	Kind      *string
	IsActive  *bool
	SortOrder *int32
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.DepotID,
		arg.Name,
		arg.Price,
		arg.Kind,
		arg.IsActive,
		arg.SortOrder,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.DepotID,
		&i.Name,
		&i.Kind,
		&i.Price,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
