// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reminders.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const reopenReminderForCancelledOrder = `-- name: ReopenReminderForCancelledOrder :exec
UPDATE reminders SET status = 'sent', order_id = NULL WHERE order_id = $1 AND status = 'ordered'
`

func (q *Queries) ReopenReminderForCancelledOrder(ctx context.Context, orderID *uuid.UUID) error {
	_, err := q.db.Exec(ctx, reopenReminderForCancelledOrder, orderID)
	return err
}
