// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countNewCustomers = `-- name: CountNewCustomers :one
SELECT count(*)::bigint FROM customers
WHERE depot_id = $1 AND created_at >= $2::timestamptz AND created_at < $3::timestamptz
`

type CountNewCustomersParams struct {
	DepotID uuid.UUID
	FromAt  time.Time
	ToAt    time.Time
}

func (q *Queries) CountNewCustomers(ctx context.Context, arg CountNewCustomersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNewCustomers, arg.DepotID, arg.FromAt, arg.ToAt)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countOrdersBySource = `-- name: CountOrdersBySource :many
SELECT source, count(*)::bigint AS total
FROM orders
WHERE depot_id = $1 AND created_at >= $2::timestamptz AND created_at < $3::timestamptz
GROUP BY source
`

type CountOrdersBySourceParams struct {
	DepotID uuid.UUID
	FromAt  time.Time
	ToAt    time.Time
}

type CountOrdersBySourceRow struct {
	Source string
	Total  int64
}

func (q *Queries) CountOrdersBySource(ctx context.Context, arg CountOrdersBySourceParams) ([]CountOrdersBySourceRow, error) {
	rows, err := q.db.Query(ctx, countOrdersBySource, arg.DepotID, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountOrdersBySourceRow{}
	for rows.Next() {
		var i CountOrdersBySourceRow
		if err := rows.Scan(&i.Source, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countOrdersByStatusForDate = `-- name: CountOrdersByStatusForDate :many
SELECT status, count(*)::bigint AS total
FROM orders
WHERE depot_id = $1 AND scheduled_date = $2::date
GROUP BY status
`

type CountOrdersByStatusForDateParams struct {
	DepotID uuid.UUID
	Day     time.Time
}

type CountOrdersByStatusForDateRow struct {
	Status string
	Total  int64
}

func (q *Queries) CountOrdersByStatusForDate(ctx context.Context, arg CountOrdersByStatusForDateParams) ([]CountOrdersByStatusForDateRow, error) {
	rows, err := q.db.Query(ctx, countOrdersByStatusForDate, arg.DepotID, arg.Day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountOrdersByStatusForDateRow{}
	for rows.Next() {
		var i CountOrdersByStatusForDateRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deliveredTotals = `-- name: DeliveredTotals :one
SELECT coalesce(sum(total), 0)::bigint AS revenue,
       coalesce(sum(refill_qty), 0)::bigint AS gallons,
       count(*)::bigint AS orders,
       count(DISTINCT customer_id)::bigint AS active_customers
FROM orders
WHERE depot_id = $1 AND status = 'delivered'
  AND delivered_at >= $2::timestamptz AND delivered_at < $3::timestamptz
`

type DeliveredTotalsParams struct {
	DepotID uuid.UUID
	FromAt  time.Time
	ToAt    time.Time
}

type DeliveredTotalsRow struct {
	Revenue         int64
	Gallons         int64
	Orders          int64
	ActiveCustomers int64
}

func (q *Queries) DeliveredTotals(ctx context.Context, arg DeliveredTotalsParams) (DeliveredTotalsRow, error) {
	row := q.db.QueryRow(ctx, deliveredTotals, arg.DepotID, arg.FromAt, arg.ToAt)
	var i DeliveredTotalsRow
	err := row.Scan(
		&i.Revenue,
		&i.Gallons,
		&i.Orders,
		&i.ActiveCustomers,
	)
	return i, err
}

const expectedDemandToday = `-- name: ExpectedDemandToday :one
SELECT coalesce(sum(c.usual_qty), 0)::bigint
FROM customers c
WHERE c.depot_id = $1 AND c.is_active AND c.is_verified
  AND c.predicted_empty_at IS NOT NULL AND c.predicted_empty_at < $2::timestamptz
  AND NOT EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = c.id AND o.status IN ('pending', 'confirmed', 'on_delivery'))
`

type ExpectedDemandTodayParams struct {
	DepotID uuid.UUID
	Before  time.Time
}

func (q *Queries) ExpectedDemandToday(ctx context.Context, arg ExpectedDemandTodayParams) (int64, error) {
	row := q.db.QueryRow(ctx, expectedDemandToday, arg.DepotID, arg.Before)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listDailyRevenue = `-- name: ListDailyRevenue :many
SELECT (delivered_at AT TIME ZONE $2::text)::date AS day,
       coalesce(sum(total), 0)::bigint AS revenue,
       coalesce(sum(refill_qty), 0)::bigint AS gallons
FROM orders
WHERE depot_id = $1 AND status = 'delivered'
  AND delivered_at >= $3::timestamptz AND delivered_at < $4::timestamptz
GROUP BY 1
ORDER BY 1
`

type ListDailyRevenueParams struct {
	DepotID uuid.UUID
	Tz      string
	FromAt  time.Time
	ToAt    time.Time
}

type ListDailyRevenueRow struct {
	Day     time.Time
	Revenue int64
	Gallons int64
}

func (q *Queries) ListDailyRevenue(ctx context.Context, arg ListDailyRevenueParams) ([]ListDailyRevenueRow, error) {
	rows, err := q.db.Query(ctx, listDailyRevenue,
		arg.DepotID,
		arg.Tz,
		arg.FromAt,
		arg.ToAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDailyRevenueRow{}
	for rows.Next() {
		var i ListDailyRevenueRow
		if err := rows.Scan(&i.Day, &i.Revenue, &i.Gallons); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveredOrdersForExport = `-- name: ListDeliveredOrdersForExport :many
SELECT o.code, o.delivered_at, o.delivery_name, o.delivery_phone, o.refill_qty, o.free_qty, o.total, o.payment_method, o.payment_status, o.source, u.name AS courier_name
FROM orders o
LEFT JOIN users u ON u.id = o.courier_id
WHERE o.depot_id = $1 AND o.status = 'delivered'
  AND o.delivered_at >= $2::timestamptz AND o.delivered_at < $3::timestamptz
ORDER BY o.delivered_at
`

type ListDeliveredOrdersForExportParams struct {
	DepotID uuid.UUID
	FromAt  time.Time
	ToAt    time.Time
}

type ListDeliveredOrdersForExportRow struct {
	Code          string
	DeliveredAt   *time.Time
	DeliveryName  string
	DeliveryPhone string
	RefillQty     int32
	FreeQty       int32
	Total         int64
	PaymentMethod *string
	PaymentStatus string
	Source        string
	CourierName   *string
}

func (q *Queries) ListDeliveredOrdersForExport(ctx context.Context, arg ListDeliveredOrdersForExportParams) ([]ListDeliveredOrdersForExportRow, error) {
	rows, err := q.db.Query(ctx, listDeliveredOrdersForExport, arg.DepotID, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeliveredOrdersForExportRow{}
	for rows.Next() {
		var i ListDeliveredOrdersForExportRow
		if err := rows.Scan(
			&i.Code,
			&i.DeliveredAt,
			&i.DeliveryName,
			&i.DeliveryPhone,
			&i.RefillQty,
			&i.FreeQty,
			&i.Total,
			&i.PaymentMethod,
			&i.PaymentStatus,
			&i.Source,
			&i.CourierName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
