// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const countActiveSessions = `-- name: CountActiveSessions :one
SELECT count(*) FROM sessions WHERE user_id = $1 AND revoked_at IS NULL AND rotated_at IS NULL AND expires_at > $2
`

type CountActiveSessionsParams struct {
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CountActiveSessions(ctx context.Context, arg CountActiveSessionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSessions, arg.UserID, arg.ExpiresAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, family_id, token_hash, expires_at, user_agent, ip)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, family_id, token_hash, expires_at, rotated_at, revoked_at, user_agent, ip, created_at
`

type CreateSessionParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	FamilyID  uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
	UserAgent string
	Ip        *netip.Prefix
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.FamilyID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.Ip,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RotatedAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.Ip,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, family_id, token_hash, expires_at, rotated_at, revoked_at, user_agent, ip, created_at FROM sessions WHERE token_hash = $1
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RotatedAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.Ip,
		&i.CreatedAt,
	)
	return i, err
}

const markSessionRotated = `-- name: MarkSessionRotated :execrows
UPDATE sessions SET rotated_at = $2 WHERE id = $1 AND rotated_at IS NULL AND revoked_at IS NULL
`

type MarkSessionRotatedParams struct {
	ID        uuid.UUID
	RotatedAt *time.Time
}

func (q *Queries) MarkSessionRotated(ctx context.Context, arg MarkSessionRotatedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markSessionRotated, arg.ID, arg.RotatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = $2 WHERE id = $1 AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	ID        uuid.UUID
	RevokedAt *time.Time
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSession, arg.ID, arg.RevokedAt)
	return err
}

const revokeSessionFamily = `-- name: RevokeSessionFamily :exec
UPDATE sessions SET revoked_at = $2 WHERE family_id = $1 AND revoked_at IS NULL
`

type RevokeSessionFamilyParams struct {
	FamilyID  uuid.UUID
	RevokedAt *time.Time
}

func (q *Queries) RevokeSessionFamily(ctx context.Context, arg RevokeSessionFamilyParams) error {
	_, err := q.db.Exec(ctx, revokeSessionFamily, arg.FamilyID, arg.RevokedAt)
	return err
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE sessions SET revoked_at = $2 WHERE user_id = $1 AND revoked_at IS NULL
`

type RevokeUserSessionsParams struct {
	UserID    uuid.UUID
	RevokedAt *time.Time
}

func (q *Queries) RevokeUserSessions(ctx context.Context, arg RevokeUserSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeUserSessions, arg.UserID, arg.RevokedAt)
	return err
}

const revokeUserSessionsExceptFamily = `-- name: RevokeUserSessionsExceptFamily :exec
UPDATE sessions SET revoked_at = $3 WHERE user_id = $1 AND family_id <> $2 AND revoked_at IS NULL
`

type RevokeUserSessionsExceptFamilyParams struct {
	UserID    uuid.UUID
	FamilyID  uuid.UUID
	RevokedAt *time.Time
}

func (q *Queries) RevokeUserSessionsExceptFamily(ctx context.Context, arg RevokeUserSessionsExceptFamilyParams) error {
	_, err := q.db.Exec(ctx, revokeUserSessionsExceptFamily, arg.UserID, arg.FamilyID, arg.RevokedAt)
	return err
}
