// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, depot_id, role, name, phone, password_hash)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, depot_id, role, name, phone, password_hash, is_active, failed_login_count, locked_until, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	ID           uuid.UUID
	DepotID      uuid.UUID
	Role         string
	Name         string
	Phone        string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.DepotID,
		arg.Role,
		arg.Name,
		arg.Phone,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DepotID,
		&i.Role,
		&i.Name,
		&i.Phone,
		&i.PasswordHash,
		&i.IsActive,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, depot_id, role, name, phone, password_hash, is_active, failed_login_count, locked_until, last_login_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DepotID,
		&i.Role,
		&i.Name,
		&i.Phone,
		&i.PasswordHash,
		&i.IsActive,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, depot_id, role, name, phone, password_hash, is_active, failed_login_count, locked_until, last_login_at, created_at, updated_at FROM users WHERE phone = $1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DepotID,
		&i.Role,
		&i.Name,
		&i.Phone,
		&i.PasswordHash,
		&i.IsActive,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserInDepot = `-- name: GetUserInDepot :one
SELECT id, depot_id, role, name, phone, password_hash, is_active, failed_login_count, locked_until, last_login_at, created_at, updated_at FROM users WHERE id = $1 AND depot_id = $2
`

type GetUserInDepotParams struct {
	ID      uuid.UUID
	DepotID uuid.UUID
}

func (q *Queries) GetUserInDepot(ctx context.Context, arg GetUserInDepotParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserInDepot, arg.ID, arg.DepotID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DepotID,
		&i.Role,
		&i.Name,
		&i.Phone,
		&i.PasswordHash,
		&i.IsActive,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveCouriers = `-- name: ListActiveCouriers :many
SELECT id, name, phone FROM users WHERE depot_id = $1 AND role = 'courier' AND is_active ORDER BY name
`

type ListActiveCouriersRow struct {
	ID    uuid.UUID
	Name  string
	Phone string
}

func (q *Queries) ListActiveCouriers(ctx context.Context, depotID uuid.UUID) ([]ListActiveCouriersRow, error) {
	rows, err := q.db.Query(ctx, listActiveCouriers, depotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveCouriersRow{}
	for rows.Next() {
		var i ListActiveCouriersRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Phone); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByDepot = `-- name: ListUsersByDepot :many
SELECT id, depot_id, role, name, phone, password_hash, is_active, failed_login_count, locked_until, last_login_at, created_at, updated_at FROM users WHERE depot_id = $1 ORDER BY role, created_at
`

func (q *Queries) ListUsersByDepot(ctx context.Context, depotID uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByDepot, depotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.DepotID,
			&i.Role,
			&i.Name,
			&i.Phone,
			&i.PasswordHash,
			&i.IsActive,
			&i.FailedLoginCount,
			&i.LockedUntil,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordLoginFailure = `-- name: RecordLoginFailure :one
UPDATE users
SET failed_login_count = failed_login_count + 1,
    locked_until = CASE WHEN failed_login_count + 1 >= $2::int THEN $3::timestamptz ELSE locked_until END,
    updated_at = now()
WHERE id = $1
RETURNING failed_login_count, locked_until
`

type RecordLoginFailureParams struct {
	ID          uuid.UUID
	MaxFailures int32
	LockUntil   time.Time
}

type RecordLoginFailureRow struct {
	FailedLoginCount int32
	LockedUntil      *time.Time
}

func (q *Queries) RecordLoginFailure(ctx context.Context, arg RecordLoginFailureParams) (RecordLoginFailureRow, error) {
	row := q.db.QueryRow(ctx, recordLoginFailure, arg.ID, arg.MaxFailures, arg.LockUntil)
	var i RecordLoginFailureRow
	err := row.Scan(&i.FailedLoginCount, &i.LockedUntil)
	return i, err
}

const recordLoginSuccess = `-- name: RecordLoginSuccess :exec
UPDATE users
SET failed_login_count = 0, locked_until = NULL, last_login_at = $2, updated_at = now()
WHERE id = $1
`

type RecordLoginSuccessParams struct {
	ID          uuid.UUID
	LastLoginAt *time.Time
}

func (q *Queries) RecordLoginSuccess(ctx context.Context, arg RecordLoginSuccessParams) error {
	_, err := q.db.Exec(ctx, recordLoginSuccess, arg.ID, arg.LastLoginAt)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2, updated_at = now() WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET name = COALESCE($3, name),
    is_active = COALESCE($4, is_active),
    updated_at = now()
WHERE id = $1 AND depot_id = $2
RETURNING id, depot_id, role, name, phone, password_hash, is_active, failed_login_count, locked_until, last_login_at, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID       uuid.UUID
	DepotID  uuid.UUID
	Name     *string
	IsActive *bool
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.DepotID,
		arg.Name,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DepotID,
		&i.Role,
		&i.Name,
		&i.Phone,
		&i.PasswordHash,
		&i.IsActive,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
